### ISSUE TITLE
Working in Firefox but not in Chrome

### ISSUE THREAD

**Issue by mdpopescu** [dotnet/try#10]
Here is what the console says when I try the first example in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in

{type: "HIDE_EDITOR"}
mscomdocs.style.app.css:14 {type: "CONFIGURE_CLIENT", client: t}
mscomdocs.style.app.css:14 {type: "NOTIFY_HOST_PROVIDED_CONFIGURATION", configuration: {…}}
mscomdocs.style.app.css:14 {type: "NOTIFY_HOST_LISTENER_READY"}
mscomdocs.style.app.css:14 {type: "LOAD_CODE_REQUEST", from: "default"}
mscomdocs.style.app.css:14 {type: "LOAD_CODE_SUCCESS", sourceCode: "using System;??public class Program?{?  public sta…ole.WriteLine("Hello!");?  }?}??Program.Main();??"}
mscomdocs.style.app.css:14 {type: "SET_CODE", sourceCode: "int[] fibarray = new int[] { 0, 1, 1, 2, 3, 5, 8, … Output:?// 0?// 1?// 1?// 2?// 3?// 5?// 8?// 13"}
mscomdocs.style.app.css:14 {type: "CONFIGURE_MONACO_EDITOR", editorOptions: {…}, theme: "vs-light"}
mscomdocs.style.app.css:14 {type: "SHOW_EDITOR"}
mscomdocs.style.app.css:14 {type: "NOTIFY_MONACO_READY", editor: t}
mscomdocs.style.app.css:14 {type: "RUN_CODE_REQUEST"}

mscomdocs.style.app.css:14 POST https://try.dot.net/workspace/workspaceId/compile?hostOrigin=https%3A%2F%2Fdocs.microsoft.com 400 (Bad Request)
(anonymous) @ mscomdocs.style.app.css:14
t.fetch @ mscomdocs.style.app.css:14
value @ mscomdocs.style.app.css:14
(anonymous) @ mscomdocs.style.app.css:14
(anonymous) @ mscomdocs.style.app.css:14
(anonymous) @ mscomdocs.style.app.css:14
postMessage (async)
DotNetOnline.run @ global.min.js?v=276:4791
(anonymous) @ global.min.js?v=276:4685
Promise resolved (async)
activateCodeBlock @ global.min.js?v=276:4678
activateCodeBlock @ global.min.js?v=276:4625
(anonymous) @ global.min.js?v=276:3712
mscomdocs.style.app.css:14 {type: "RUN_CODE_FAILURE", ex: Error: FetchError: {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"…}
global.min.js?v=276:4822 timeout
(anonymous) @ global.min.js?v=276:4822
Promise rejected (async)
DotNetOnline.run @ global.min.js?v=276:4817
(anonymous) @ global.min.js?v=276:4685
Promise resolved (async)
activateCodeBlock @ global.min.js?v=276:4678
activateCodeBlock @ global.min.js?v=276:4625
(anonymous) @ global.min.js?v=276:3712

{type: "RUN_CODE_FAILURE", ex: Error: FetchError: {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"…}
global.min.js?v=276:4822 timeout
(anonymous) @ global.min.js?v=276:4822
Promise rejected (async)
DotNetOnline.run @ global.min.js?v=276:4817
(anonymous) @ global.min.js?v=276:4685
Promise resolved (async)
activateCodeBlock @ global.min.js?v=276:4678
activateCodeBlock @ global.min.js?v=276:4625
(anonymous) @ global.min.js?v=276:3712

global.min.js?v=276:4822 timeout
(anonymous) @ global.min.js?v=276:4822
Promise rejected (async)
DotNetOnline.run @ global.min.js?v=276:4817
(anonymous) @ global.min.js?v=276:4685
Promise resolved (async)
activateCodeBlock @ global.min.js?v=276:4678
activateCodeBlock @ global.min.js?v=276:4625
(anonymous) @ global.min.js?v=276:3712

**Comment by piotrpMSFT** [comment]
@mdpopescu we're having no luck reproducing this problem. If you are still seeing it, can you look at your `F12` developer tools and share the `Request-ID` header from any failing requests made against `try.dot.net`?

**Comment by mdpopescu** [comment]
This is everything I get in ex; in particular, one request id is "|781f013e-460da5b0b065d041.1.2.54.1.":

Error: FetchError: {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"map":{"pragma":"no-cache","content-security-policy":"default-src 'none';script-src 'self' https: 'sha256-d5A9Nyiy3cKXUJQQe6MAmlwRhXsnzKsKBJdUrPUzW6U=' 'sha256-4TIZYBy2wGTYb3T7Bl+gpip7IxpeeJR7L9Dc6Nl5lyw=';style-src 'self' https: 'unsafe-inline';child-src 'self';connect-src 'self' https:;img-src 'self' https: data:;frame-ancestors https://docs.microsoft.com","x-content-type-options":"nosniff","date":"Tue, 17 Oct 2017 19:57:34 GMT","cache-control":"no-cache, no-store","request-id":"|781f013e-460da5b0b065d041.1.2.54.1.","content-length":"0","request-context":"appId=cid-v1:6d77e5f7-edb8-4a0c-93c9-6b73815c67d2","content-type":"text/xml"}},"url":"https://try.dot.net/workspace/workspaceId/compile?hostOrigin=https%3A%2F%2Fdocs.microsoft.com","_bodyInit":{},"_bodyBlob":{}} at https://try.dot.net/bundle.js:25:183221 at <anonymous>
message
:
"FetchError: {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"map":{"pragma":"no-cache","content-security-policy":"default-src 'none';script-src 'self' https: 'sha256-d5A9Nyiy3cKXUJQQe6MAmlwRhXsnzKsKBJdUrPUzW6U=' 'sha256-4TIZYBy2wGTYb3T7Bl+gpip7IxpeeJR7L9Dc6Nl5lyw=';style-src 'self' https: 'unsafe-inline';child-src 'self';connect-src 'self' https:;img-src 'self' https: data:;frame-ancestors https://docs.microsoft.com","x-content-type-options":"nosniff","date":"Tue, 17 Oct 2017 19:57:34 GMT","cache-control":"no-cache, no-store","request-id":"|781f013e-460da5b0b065d041.1.2.54.1.","content-length":"0","request-context":"appId=cid-v1:6d77e5f7-edb8-4a0c-93c9-6b73815c67d2","content-type":"text/xml"}},"url":"https://try.dot.net/workspace/workspaceId/compile?hostOrigin=https%3A%2F%2Fdocs.microsoft.com","_bodyInit":{},"_bodyBlob":{}}"
stack
:
"Error: FetchError: {"type":"default","status":400,"ok":false,"statusText":"Bad Request","headers":{"map":{"pragma":"no-cache","content-security-policy":"default-src 'none';script-src 'self' https: 'sha256-d5A9Nyiy3cKXUJQQe6MAmlwRhXsnzKsKBJdUrPUzW6U=' 'sha256-4TIZYBy2wGTYb3T7Bl+gpip7IxpeeJR7L9Dc6Nl5lyw=';style-src 'self' https: 'unsafe-inline';child-src 'self';connect-src 'self' https:;img-src 'self' https: data:;frame-ancestors https://docs.microsoft.com","x-content-type-options":"nosniff","date":"Tue, 17 Oct 2017 19:57:34 GMT","cache-control":"no-cache, no-store","request-id":"|781f013e-460da5b0b065d041.1.2.54.1.","content-length":"0","request-context":"appId=cid-v1:6d77e5f7-edb8-4a0c-93c9-6b73815c67d2","content-type":"text/xml"}},"url":"https://try.dot.net/workspace/workspaceId/compile?hostOrigin=https%3A%2F%2Fdocs.microsoft.com","_bodyInit":{},"_bodyBlob":{}}?    at https://try.dot.net/bundle.js:25:183221?    at <anonymous>"

**Comment by piotrpMSFT** [comment]
I'm speculating you may have stale client bits. We've seen some similar issues due to caching. Can you try doing a hard refresh `Ctrl+F5` or browsing to the page with an in-private browsing session?

**Comment by mdpopescu** [comment]
I am sorry, it's almost midnight and I'm no longer at the computer. I will
try that in about 9 hours. Sorry to have given you extra work.

**Comment by piotrpMSFT** [comment]
Thanks @mdpopescu. No problem. We really appreciate the issue report as we want the service to be as stable as possible!

**Comment by mdpopescu** [comment]
I tried both, it didn't help.

This is the contents of the Headers tab in Chrome F12 from the XHR failure during the incognito session:

===
Request URL:https://try.dot.net/workspace/workspaceId/compile?hostOrigin=https%3A%2F%2Fdocs.microsoft.com
Request Method:POST
Status Code:400 Bad Request
Remote Address:13.93.220.109:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:no-cache, no-store
Content-Length:0
Content-Security-Policy:default-src 'none';script-src 'self' https: 'sha256-d5A9Nyiy3cKXUJQQe6MAmlwRhXsnzKsKBJdUrPUzW6U=' 'sha256-4TIZYBy2wGTYb3T7Bl+gpip7IxpeeJR7L9Dc6Nl5lyw=';style-src 'self' https: 'unsafe-inline';child-src 'self';connect-src 'self' https:;img-src 'self' https: data:;frame-ancestors https://docs.microsoft.com
Date:Wed, 18 Oct 2017 05:14:48 GMT
Pragma:no-cache
Request-Context:appId=cid-v1:6d77e5f7-edb8-4a0c-93c9-6b73815c67d2
Request-Id:|54a4c018-4046ee9abed59dfe.1.2.215.1.
Set-Cookie:XSRF-TOKEN=CfDJ8CPM_Xazl2BLkflyez3VtptKqOMUlwaMle_PpvdG7R6qis77mF3kRawH0--pnmXVQwnLeVX7euo48xh99QMauLoXrtCpy1n-TqkZ4k8wVE06Y4oIzBDIuQl-99UFfqyBlcCKYJqDcVrMFe7ZAV8ya9s; path=/; secure
Set-Cookie:ARRAffinity=55ca23a0fbf5aaa0bb74f36caa9d43567747442b37c3d80ab1c7dfb6ff8e6e19;Path=/;HttpOnly;Domain=try.dot.net
Set-Cookie:CSRF-TOKEN=CfDJ8CPM_Xazl2BLkflyez3Vtpsn5yt5sZR52ScHaTqNu1YZYFF92tWW9-6_jTN1P-Rxf5ryd6BUB1Ewwk-jHSF5D2PAm6_5EaY3_M0ZBnoTijA7kVDPPqMNW3Jz_12EehMXoHV51V4_l3_dx53ujUech9A; path=/; httponly
X-Content-Type-Options:nosniff
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,ro;q=0.6
Connection:keep-alive
Content-Length:239
content-type:application/json
DNT:1
Host:try.dot.net
Origin:https://try.dot.net
Referer:https://try.dot.net/editor?hostOrigin=https%3A%2F%2Fdocs.microsoft.com&waitForConfiguration=true&debug=true
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Query String Parameters
view source
view URL encoded
hostOrigin:https://docs.microsoft.com
Request Payload
view parsed
{"Source":"int[] fibarray = new int[] { 0, 1, 1, 2, 3, 5, 8, 13 };\nforeach (int element in fibarray)\n{\n    System.Console.WriteLine(element);\n}\nSystem.Console.WriteLine();\n// Output:\n// 0\n// 1\n// 1\n// 2\n// 3\n// 5\n// 8\n// 13"}
===

I guess... just leave this as a low-priority issue (or close it) then, unless someone else reports problems?

Thanks.

**Comment by jonsequitur** [comment]
@mdpopescu Do you still see this issue?

**Comment by mdpopescu** [comment]
I get this message:

The service is temporarily unavailable. We are working on it.

I am attaching the console 
[docs.microsoft.com-1515595997751.log](https://github.com/dotnet/try/files/1619272/docs.microsoft.com-1515595997751.log)
