### ISSUE TITLE
Extension methods are not supported

### ISSUE THREAD

**Issue by loic-sharma** [dotnet/try#101]
The following snippet:

```csharp
public static class X
{
  public static void Test(this string t)
  {
    Console.WriteLine($"Value {t}");
  }
}

public class Program
{
  public static void Main()
  {
    string foo = null;

    foo.Test();
  }
}
```

Gives the following build errors:

> (2,22): error CS1109: Extension methods must be defined in a top level static class; X is a nested class
> (14,9): error CS1061: 'string' does not contain a definition for 'Test' and no extension method 'Test' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)

**Comment by jonsequitur** [comment]
This is a consequence of the default Try .NET experience using C# scripting. If you switch to the full .NET Core experience (https://try.dot.net/?workspaceType=console) this will work.

**Comment by svick** [comment]
Also, it does work if you declare the extension method outside the class:

```c#
public static void Test(this string t)
{
  Console.WriteLine($"Value {t}");
}

public class Program
{
  public static void Main()
  {
    string foo = null;

    foo.Test();
  }
}
```
