### ISSUE TITLE
[Accessibility]A11y_.NET Online REPL View_Keyboard: When the user selects "Enter focus mode" button, on next tab key press , focus should go to the first line of the editor, but the focus is going to "Previous" button

### ISSUE THREAD

**Issue by soumyatippapuram** [dotnet/try#103]
**Environment Details:** 
URL: https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=1
Browser: Edge 42.17134.1.0 , Chrome 67.0.3396.87

**Repro Steps:**
1)Hit the URL : https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=1
2)Tab till "Enter focus mode" button and press enter
3)Editor pane will open up
4)Press tab key to check for next tab stop

**Actual Result:**
When the user selects "Enter focus mode" button, on next tab key press , focus should go to the first line of the editor, but the focus is going to "Previous" button

**Expected Result:**
When the user selects "Enter focus mode" button, on next tab key press , focus should go to the first line of the editor

**User Impact:** 
Keyboard only users may get confused

**MAS Reference:** 
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}
[Focus Order Issue foe Enter focus mode.pptx](https://github.com/dotnet/try/files/2188257/Focus.Order.Issue.foe.Enter.focus.mode.pptx)

**Comment by LadyNaggaga** [comment]
Issue has been flagged and assigned to the Monaco repo.
https://github.com/Microsoft/monaco-editor/issues/1163

**Comment by LadyNaggaga** [comment]
1.	Importance of experience (High or Low Impact). 
Impact: Low we haven't received any customer complaints directly to the service. The .NET online editor is the service behind editor and we do not own or control the UI experience. 
Describe scenario: Please the description above
2.	Quality of Experience (High or Low Impact). 
Impact: Low we haven't received any customer complaints directly to the service. The .NET online editor is the service behind editor and we do not own or control the UI experience. 
3.	[Link to AAT ](https://cela-ra-aat-prod.azurewebsites.net/#/workflow/93711e75-9cb7-4061-b1e9-53177a087cae)
4.	Any alternate solutions or technologies evaluated
Not applicable 
5.	Ensure all evidence for hand-off to external team is provided in the bug
Issue has been flagged and assigned to the Monaco repo.
https://github.com/Microsoft/monaco-editor/issues/1163

**Comment by umasarath52** [comment]
This was discussed with Ryan and approved to close as this is non blocking scenario.
