### ISSUE TITLE
Re-establish our integration testing with PeakyTests

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/try#1131]
We have a good validation set with https://github.com/PeakyTests/Peaky that need to be re-enabled to improve our confidence for the deployment.

**Comment by AbhitejJohn** [comment]
@jonsequitur : Please add more color to this if needed.

**Comment by ocallesp** [comment]
@jonsequitur is working on a fix for the Peaky package.

after the fix we can port the Peaky tests from the old codebase to this repo.

**Comment by AbhitejJohn** [comment]
This is done.
