### ISSUE TITLE
Consolidate fixes in our yml pipelines

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/try#1150]
Currently any fixes in the yml needs updates in 3 different places:
1. https://github.com/dotnet/try/blob/main/azure-pipelines-CI.yml
2. https://github.com/dotnet/try/blob/main/azure-pipelines.yml
3. https://devdiv.visualstudio.com/DefaultCollection/Engineering/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=21351&branch=InitialSetup

That's a good amount of yml duplication. Investigate if we can use a template that we can pull into all these yml files to make this easier.

**Comment by ocallesp** [comment]
Doing some refactor only:
- https://github.com/dotnet/try/blob/main/azure-pipelines-CI.yml
- https://github.com/dotnet/try/blob/main/azure-pipelines.yml
