### ISSUE TITLE
Compile errors are duplicated in output

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/try#1184]
![image](https://github.com/dotnet/try/assets/547415/66a53b5e-6894-407c-8615-540a7a98a090)

**Comment by ocallesp** [comment]
This bug doesn't repro


https://learn.microsoft.com/en-us/training/modules/csharp-write-first/2-exercise-hello-world
![image](https://github.com/dotnet/try/assets/510598/a21f4771-4080-43e6-88b3-6e129b1ce67e)



https://dotnet.microsoft.com/en-us/learn/dotnet/in-browser-tutorial/1
![image](https://github.com/dotnet/try/assets/510598/0da2b9f0-e70b-4838-b5e4-3f6bdeb197d9)


mock project
![image](https://github.com/dotnet/try/assets/510598/8af712c9-5a39-4426-9de4-e738c0826a16)

**Comment by jonsequitur** [comment]
The repro is visible in your screen shots.

**Comment by ocallesp** [comment]
> The repro is visible in your screen shots.
> 
> The following are duplicates, one containing a line number and the other not containing it.
> 
> ```
> (2,1): error CS0103: The name 'hmm' does not exist in the current context
> ; expected
> The name 'hmm' does not exist in the current context
> ```

These are two different compiler error numbers which doesn't count as a duplicated output.

In the original image you posted it appears twice each error number.

Are you considering this ?

**Comment by jonsequitur** [comment]
The bug is that the error message `The name 'hmm' does not exist in the current context` is shown twice in the output.
