### ISSUE TITLE
Console Output shows many "Errors on load"

### ISSUE THREAD

**Issue by ocallesp** [dotnet/try#1199]
-  Investigate

**Comment by AbhitejJohn** [comment]
Additional context: This shows up onload of the marketing page as well.

**Comment by ocallesp** [comment]
Investigating this issue....
@AbhitejJohn

**Comment by jonsequitur** [comment]
Is this still happening? The repro steps are unclear.

**Comment by ocallesp** [comment]
I tried a couple of times last week and couldn't repro this issue anymore. I confirmed this with Dan
