### ISSUE TITLE
Feedback link is visually appearing as button: A11y_.NET Online REPL_NET Editor_Feedback_Usability.

### ISSUE THREAD

**Issue by AnKushSingh05** [dotnet/try#1202]
### GitHub Tags
#A11yTCS; #A11ySev4; #Chromiumedge; #A11yUsable; #SH_.NET Online REPL_Web_May2024; #DesktopWeb; #TryDotNet;#Win11;

### Environment Details:
Application Name: .NET Online REPL
Chromium edge Version 125.0.2535.51 (Official build) (64-bit)

### Repro Steps:

1. Hit the URL: https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp?tutorial-step=1
2. .NET Editor page will open.
3. Tab till feedback link.
4. Verify whether the Feedback link is visually appearing as button or not.

###  Actual Result:

Feedback link is visually appearing as button which is incorrect.

### Expected Result:
Feedback link should visually also appear as link because programmatically they are defined as link.

### User Impact:
Users will get confused if link is appearing as button.
### Attachment:
![Bug_1202_A11y_ NET Online REPL](https://github.com/dotnet/try/assets/124244478/9ebd8df8-26f2-43f6-94ba-fbc4f4595266)

**Comment by Yash14j** [comment]
GithubTags:#Rev:yaja;

**Comment by AbhitejJohn** [comment]
@Yash14j / @AnKushSingh05 : Should this test have actually been run on the [PPE environment](https://review.learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp?tutorial-step=1&preview=try-dotnet-ppe&branch=main) instead of what you have in the repro steps? 
/cc: @ocallesp

**Comment by jonsequitur** [comment]
This element is not coming from Try .NET. Please reopen this issue on Learn.
