### ISSUE TITLE
Warnings are being treated as errors and preventing program output from being shown

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/try#1213]
![image](https://github.com/dotnet/try/assets/547415/166c6b49-5147-43d9-b9fa-6f7fec46c2a3)

**Comment by ocallesp** [comment]
@jonsequitur 
I cannot reproduce this bug locally or on the Learning or Marketing servers. Can you try to repro it again ?
Here are the links I used
- [Learn](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp?tutorial-step=1)
- [Marketing](https://dotnet.microsoft.com/en-us/learn/dotnet/in-browser-tutorial/1)

![TryDotNetIssue](https://github.com/dotnet/try/assets/510598/bfe588cb-eea0-4b2e-ac77-46aa27d91b21)
