### ISSUE TITLE
https://try.dot.net under maintenance

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/try#1218]
The old [try.dot.net](https://try.dot.net) site is in the process of being redirected to https://dotnet.microsoft.com/en-us/platform/try-dotnet, which provides more context and information about Try .NET. 

Until the automatic redirect is in place, you can go directly to https://dotnet.microsoft.com/en-us/platform/try-dotnet and use the Try .NET editor there, which now supports C# 12.

**Comment by CalebBellWebCE** [comment]
I often used https://try.dot.net to quickly validate my assumptions about how basic things worked in C# (e.g. what is the outcome of `5 < (int?)null` ?).  The new site informs me about interesting features that would be useful if I were sharing content, but it is distinctly worse as a C# sandbox.  Is there a replacement full-screen C# sandbox that I should use instead?  Or should I host my own?

**Comment by jonsequitur** [comment]
I've passed this feedback along.

We would like to make Try .NET easier to host and customize, and the latest updates have moved it in that direction. But currently hosting your own is pretty non-trivial.

Another quick experimentation option of course is [Polyglot Notebooks](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).

**Comment by dalehhirt** [comment]
This should be resolved.  We are waiting for a day, and then will close out the issue.
