### ISSUE TITLE
More than two periods in a row in the code will not work

### ISSUE THREAD

**Issue by mogura0529** [dotnet/try#1240]
#### Describe the bug
Please provide as much information as you can.
If Console.Write or comment contains a code with two or more consecutive periods, the value will not be output correctly.

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [x] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![Image](https://github.com/user-attachments/assets/40c1f62a-f1d6-4572-a22f-a4165b140102)
![Image](https://github.com/user-attachments/assets/7186de0d-2a36-433f-b62c-06f617f94de7)

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] Windows 11
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome/
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
This is causing a CORS error. It looks like the specific string that triggers it is `.."` occurring anywhere in the code submission.

For example, this will work (note the `..` in the second line):

```csharp
List<int> xs = [1, 2, 3, 4, 5];
Console.WriteLine(xs[2..].Count);
```

But this will trigger the error: 

```csharp
List<int> xs = [1, 2, 3, 4, 5];
// .."
Console.WriteLine(xs[2..].Count);
```

**Comment by jonsequitur** [comment]
This is now fixed. Thanks for opening this issue @mogura0529!
