### ISSUE TITLE
Experience: Option 3 - VS download dismissed - Ubuntu 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/try#127]
Scenario:  A user is presented with the option to download Code  post first run.  In this experience the user can easily dismiss this "banner" and reopen it if they need to

### Ubuntu Experience 

- [ ] User starts one of the Quick Starts
<img width="700" alt="vs1" src="https://user-images.githubusercontent.com/2546640/42781164-5699294c-8913-11e8-8c55-69395435e717.PNG">

- [ ] User hits the run button 
<img width="700" alt="vs2" src="https://user-images.githubusercontent.com/2546640/42781189-68a8c174-8913-11e8-80b9-57d1ed72c733.PNG">

- [ ] "Banner" appears; notifying that user they can download Code
<img width="700" alt="code3" src="https://user-images.githubusercontent.com/2546640/42781229-8b692410-8913-11e8-82b4-545113105b55.PNG">

- [ ] User can minimize the "banner".
<img width="700" alt="code4" src="https://user-images.githubusercontent.com/2546640/42781279-b111eecc-8913-11e8-9657-c248c1175738.PNG">

- [ ] Code Icon remains as a minimized menu
<img width="700" alt="code5" src="https://user-images.githubusercontent.com/2546640/42781334-d74cf898-8913-11e8-8635-ef141a801ff6.PNG">

- [ ]  User continues to next step . The minimized menu still appears in the lower right corner on editor window.
<img width="700" alt="code6" src="https://user-images.githubusercontent.com/2546640/42781397-08e273b0-8914-11e8-91ca-42413ce03be9.PNG">

- [ ] User can click on the Code Icon to reveal the full "banner".
<img width="700" alt="code7" src="https://user-images.githubusercontent.com/2546640/42781450-2f070cae-8914-11e8-8c75-de8805d7e20c.PNG">

- [ ] full "banner" reappears.
<img width="700" alt="code8" src="https://user-images.githubusercontent.com/2546640/42781543-6cffcf32-8914-11e8-9a58-6bc39c74df71.PNG">

- [ ] User clicks on work locally to prompt download
<img width="700" alt="code9" src="https://user-images.githubusercontent.com/2546640/42781630-a41305ac-8914-11e8-9238-7ea6916a89e1.PNG">

**Comment by akshita31** [comment]
Visual Studio Code is not a full-fledged IDE, it is more of an editor and to enable the C# capabilities we need to download the C# extension separately. So, is it fair to link the user from try.dot.net to an editor which by default does not have the C# support?
