### ISSUE TITLE
The Console.WriteLine() statement doesn't create a blank line.

### ISSUE THREAD

**Issue by MichaelMoosman** [dotnet/try#128]
var names = new List<string> { "<name>", "Ana", "Felipe" };
foreach (var name in names)
{
    Console.WriteLine($"Hello {name.ToUpper()}!");
}

Console.WriteLine(); // This should create a blank line, but doesn't - This is part of the List Collections quickstart tutorial.
names.Add("Maria");
names.Add("Bill");
names.Remove("Ana");

**Comment by TheRealPiotrP** [comment]
@MichaelMoosman thanks for the report. this was fixed recently. I updated your sample to better show the change:

```
var names = new List<string> { "", "Ana", "Felipe" };
foreach (var name in names)
{
Console.WriteLine($"Hello {name.ToUpper()}!");
}

Console.WriteLine(); // This should create a blank line, but doesn't - This is part of the List Collections quickstart tutorial.
names.Add("Maria");
names.Add("Bill");
names.Remove("Ana");

foreach (var name in names)
{
  Console.WriteLine($"Hello {name.ToUpper()}!");
}
```

Which now outputs:
```
Hello !
Hello ANA!
Hello FELIPE!

Hello !
Hello FELIPE!
Hello MARIA!
Hello BILL!
```

Notice that the empty line is maintained!
