### ISSUE TITLE
Mistake in sample code provided in .Net tutorial using c#

### ISSUE THREAD

**Issue by crypto166** [dotnet/try#129]
Interpolated string chapter // Page 2
public class Vegetable
{
   public Vegetable(string name) => Name = name;

   public string Name { get; }

   public override string ToString() => Name;
}

public enum Unit { item, pound, ounce, dozen };

var item = new Vegetable("eggplant");
var date = DateTime.Now;
var price = 1.99m;
var unit = Unit.item;
Console.WriteLine($"On {date}, the price of {item} was {price} per {unit}.");

HERE IN THE LAST LINE {unit} must be unit .
This might cause problem for beginners .

**Comment by MaximRouiller** [comment]
This code works as expected on my end. We're showing the date, the price of the item as well as the unit of the price of the item.

What were your expectations?

**Comment by TheRealPiotrP** [comment]
I'm closing this as it appears by-design and we haven't seen any traction in the past month. Please open a new issue with clearer description if there's something else going on here.
