### ISSUE TITLE
Interactive samples don't work because of missing namespace using

### ISSUE THREAD

**Issue by svick** [dotnet/try#130]
When I go to [Custom numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) and try to run the first sample, I get many errors:

> (19,2): error CS0246: The type or namespace name 'CultureInfo' could not be found (are you missing a using directive or an assembly reference?)
(36,2): error CS0246: The type or namespace name 'CultureInfo' could not be found (are you missing a using directive or an assembly reference?)
(9,43): error CS0103: The name 'CultureInfo' does not exist in the current context
(10,34): error CS0103: The name 'CultureInfo' does not exist in the current context
(14,44): error CS0103: The name 'CultureInfo' does not exist in the current context
(15,34): error CS0103: The name 'CultureInfo' does not exist in the current context
(19,21): error CS0103: The name 'CultureInfo' does not exist in the current context
(25,42): error CS0103: The name 'CultureInfo' does not exist in the current context
(26,34): error CS0103: The name 'CultureInfo' does not exist in the current context
(31,42): error CS0103: The name 'CultureInfo' does not exist in the current context
(32,34): error CS0103: The name 'CultureInfo' does not exist in the current context
(36,21): error CS0103: The name 'CultureInfo' does not exist in the current context
(42,44): error CS0103: The name 'CultureInfo' does not exist in the current context
(43,34): error CS0103: The name 'CultureInfo' does not exist in the current context
(48,45): error CS0103: The name 'CultureInfo' does not exist in the current context
(49,34): error CS0103: The name 'CultureInfo' does not exist in the current context

It seems the snippet is compiled without the necessary `using System.Globalization;`, even though [the source file that contains the snippet does have it](https://github.com/dotnet/samples/blob/7c589b8/snippets/csharp/VS_Snippets_CLR/formatting.numeric.custom/cs/custom.cs). I think this should work and it could even be a regression.

**Comment by BillWagner** [comment]
ping @TheRealPiotrP Did this change?

**Comment by TheRealPiotrP** [comment]
Sorry folks, I had missed this somehow. Looking now.

**Comment by TheRealPiotrP** [comment]
@jonsequitur @colombod @rchande

**Comment by jonsequitur** [comment]
It seems that the additional `using` for `System.Globalization` is not being sent by the hosting page. @jdanyow Do you know if there was a change in the docs integration?

**Comment by jdanyow** [comment]
@jonsequitur not sure- I don't know how the snippets integration works.  @dend do you know who can help with this?

- [custom-numeric-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) page
- first code block with the run button has the following markdown source code:
  ```md
   [!code-csharp-interactive[Formatting.Numeric.Custom#1](../../../samples/snippets/csharp/VS_Snippets_CLR/formatting.numeric.custom/cs/custom.cs#1)]
  ```
- This references the following snippet:
  https://github.com/dotnet/samples/blob/3c63059bea2fb4c39f54fccd8f72faa97b0ebdb2/snippets/csharp/VS_Snippets_CLR/formatting.numeric.custom/cs/custom.cs#L38-L90
- The `using` statements at the top of the snippet cs file are not transferring to the docs content... should they?
  https://github.com/dotnet/samples/blob/3c63059bea2fb4c39f54fccd8f72faa97b0ebdb2/snippets/csharp/VS_Snippets_CLR/formatting.numeric.custom/cs/custom.cs#L1-L2

**Comment by jonsequitur** [comment]
After a little more digging, it seems like the page isn't specifying usings when sending `SET_WORKSPACE` to the Try .NET postMessage API. Here's the debug output:

```
{type: "SET_WORKSPACE_TYPE", workspaceType: "script"}type: "SET_WORKSPACE_TYPE"workspaceType: "script"__proto__: Object
{type: "SET_WORKSPACE", workspace: {…}}type: "SET_WORKSPACE"workspace: buffers: [{…}]0: {id: "", content: "", position: 0}content: ""id: ""position: 0__proto__: Objectlength: 1__proto__: Array(0)files: []length: 0__proto__: Array(0)_usings: Array(0)_length: 0__proto__: Array(0)workspaceType: "script"__proto__: Object__proto__: Object
{type: "SET_ACTIVE_BUFFER", bufferId: ""}bufferId: ""type: "SET_ACTIVE_BUFFER"__proto__: Object
{type: "CONFIGURE_COMPLETION_PROVIDER", completionProvider: "pythia"}
{type: "HIDE_EDITOR"}
{type: "CONFIGURE_CLIENT", client: e}
{type: "NOTIFY_HOST_PROVIDED_CONFIGURATION", configuration: {…}}
{type: "NOTIFY_HOST_LISTENER_READY"}
{type: "LOAD_CODE_REQUEST", from: "default"}from: "default"type: "LOAD_CODE_REQUEST"__proto__: Object
{type: "LOAD_CODE_SUCCESS", sourceCode: "using System;↵using System.Collections.Generic;↵us…  next = current + (current = next);↵    }↵  }↵}↵", bufferId: ""}bufferId: ""sourceCode: "using System;↵using System.Collections.Generic;↵using System.Linq;↵↵public class Program↵{↵  public static void Main()↵  {↵    foreach (var i in Fibonacci().Take(20))↵    {↵      Console.WriteLine(i);↵    }↵  }↵↵  private static IEnumerable<int> Fibonacci()↵  {↵    int current = 1, next = 1;↵↵    while (true) ↵    {↵      yield return current;↵      next = current + (current = next);↵    }↵  }↵}↵"type: "LOAD_CODE_SUCCESS"__proto__: Object
{type: "CONFIGURE_VERSION", version: 2}
{type: "UPDATE_WORKSPACE_BUFFER", content: "", bufferId: ""}bufferId: ""content: ""type: "UPDATE_WORKSPACE_BUFFER"__proto__: Object
{type: "CONFIGURE_MONACO_EDITOR", editorOptions: {…}, theme: "vs-light"}
{type: "SHOW_EDITOR"}
{type: "NOTIFY_MONACO_READY", editor: t}
{type: "UPDATE_WORKSPACE_BUFFER", content: "double value;↵ ↵ value = 123;↵ Console.WriteLine(v…    "{0:0,0.00}", value));	↵ // Displays 1,234.57", bufferId: ""}bufferId: ""content: "double value;↵ ↵ value = 123;↵ Console.WriteLine(value.ToString("00000"));↵ Console.WriteLine(String.Format("{0:00000}", value));↵ // Displays 00123↵ ↵ value = 1.2;↵ Console.WriteLine(value.ToString("0.00", CultureInfo.InvariantCulture));↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                   "{0:0.00}", value));↵ // Displays 1.20↵↵ Console.WriteLine(value.ToString("00.00", CultureInfo.InvariantCulture));↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                                 "{0:00.00}", value));↵ // Displays 01.20↵↵ CultureInfo daDK = CultureInfo.CreateSpecificCulture("da-DK");↵ Console.WriteLine(value.ToString("00.00", daDK)); ↵ Console.WriteLine(String.Format(daDK, "{0:00.00}", value));↵ // Displays 01,20↵ ↵ value = .56;↵ Console.WriteLine(value.ToString("0.0", CultureInfo.InvariantCulture));↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                                 "{0:0.0}", value));↵ // Displays 0.6↵↵ value = 1234567890;↵ Console.WriteLine(value.ToString("0,0", CultureInfo.InvariantCulture));	↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                                 "{0:0,0}", value));	↵ // Displays 1,234,567,890      ↵ ↵ CultureInfo elGR = CultureInfo.CreateSpecificCulture("el-GR");↵ Console.WriteLine(value.ToString("0,0", elGR));	↵Console.WriteLine(String.Format(elGR, "{0:0,0}", value));	↵ // Displays 1.234.567.890↵ ↵ value = 1234567890.123456;↵ Console.WriteLine(value.ToString("0,0.0", CultureInfo.InvariantCulture));	↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                                 "{0:0,0.0}", value));	↵ // Displays 1,234,567,890.1  ↵ ↵ value = 1234.567890;↵ Console.WriteLine(value.ToString("0,0.00", CultureInfo.InvariantCulture));	↵ Console.WriteLine(String.Format(CultureInfo.InvariantCulture, ↵                                 "{0:0,0.00}", value));	↵ // Displays 1,234.57"type: "UPDATE_WORKSPACE_BUFFER"__proto__: Object
{type: "RUN_CODE_REQUEST"}type: "RUN_CODE_REQUEST"__proto__: Object
{type: "RUN_CODE_SUCCESS", exception: null, output: Array(16), succeeded: false, diagnostics: Array(16), …}diagnostics: (16) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]exception: nullinstrumentation: undefinedoutput: (16) ["(19,2): error CS0246: The type or namespace name '…sing a using directive or an assembly reference?)", "(36,2): error CS0246: The type or namespace name '…sing a using directive or an assembly reference?)", "(9,43): error CS0103: The name 'CultureInfo' does not exist in the current context", "(10,34): error CS0103: The name 'CultureInfo' does not exist in the current context", "(14,44): error CS0103: The name 'CultureInfo' does not exist in the current context", "(15,34): error CS0103: The name 'CultureInfo' does not exist in the current context", "(19,21): error CS0103: The name 'CultureInfo' does not exist in the current context", "(25,42): error CS0103: The name 'CultureInfo' does not exist in the current context", "(26,34): error CS0103: The name 'CultureInfo' does not exist in the current context", "(31,42): error CS0103: The name 'CultureInfo' does not exist in the current context", "(32,34): error CS0103: The name 'CultureInfo' does not exist in the current context", "(36,21): error CS0103: The name 'CultureInfo' does not exist in the current context", "(42,44): error CS0103: The name 'CultureInfo' does not exist in the current context", "(43,34): error CS0103: The name 'CultureInfo' does not exist in the current context", "(48,45): error CS0103: The name 'CultureInfo' does not exist in the current context", "(49,34): error CS0103: The name 'CultureInfo' does not exist in the current context"]succeeded: falsetype: "RUN_CODE_SUCCESS"variableLocations: undefined__proto__: Object
{type: "RUN_CODE_REQUEST"}type: "RUN_CODE_REQUEST"__proto__: Object
{type: "RUN_CODE_SUCCESS", exception: null, output: Array(16), succeeded: false, diagnostics: Array(16), …}

```

**Comment by jdanyow** [comment]
@jonsequitur I don't think docs has ever sent a message via the postMessage API related to using statements. Here are the message types docs sends via the postMessage API:

- configureMonacoEditor: to set the theme
- setSourceCode: the text from the code block where the run button was clicked
- showEditor
- focusEditor
- run

**Comment by dend** [comment]
@jonsequitur @jdanyow I see two paths here:

* **Short-term** - guide writers to show snippets that have a `using` statement, where applicable.
* **Long-term** - have a feature that allows us to aggregate and pass `using` statements - I don't think we keep them in our pipeline in any shape or form today after the HTML content is built.

Thoughts on the above?

**Comment by rpetrusha** [comment]
I'm fairly certain that this is a regression, though. I'm almost completely positive that I tested the custom date and time format string topics before actually publishing the topic, and they worked.

**Comment by jonsequitur** [comment]
@dend We do support adding custom `using`s. The postMessage API for this is documented here: https://try.dot.net/docs.

**Comment by rpetrusha** [comment]
Thanks, @jonsequitur.

**Comment by jonsequitur** [comment]
This is now fixed in production. Please note that the error may still be served from the cache for a few days. A trivial change to the code samples would prevent that.
