### ISSUE TITLE
Typo on name in example for C# tutorial

### ISSUE THREAD

**Issue by McHelpin** [dotnet/try#133]
aFriend = "Maira";

https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=2

Is this supposed to be Maria? If not please disregard this issue.

Thanks!

**Comment by BillWagner** [comment]
> Is this supposed to be Maria? If not please disregard this issue.

@McHelpin We've used both:  @LadyNaggaga and @mairaw both work on this experience. 

Closing.
