### ISSUE TITLE
pt-br: O serviço está temporariamente indisponível.

### ISSUE THREAD

**Issue by nephew92** [dotnet/try#134]
A aba do compilador informa esta mensagem. O problema aconteceu neste momento.
Uso o navegador Chrome sobre o Ubuntu 16.04

**Comment by nephew92** [comment]
Hi!
Of course, I do.
I'm using the portuguese version of the site (docs.microsoft.com/pt-br) and
the online C# compiler isn't running. A short time aftet I click on "Run
code" is shown a message that the service is not avaiable. This is happened
ever.
*__________________________________________________________*
Francisco Sobrinho  <http://lattes.cnpq.br/6916947700958849>




Em ter, 7 de ago de 2018 às 12:23, LadyNaggaga <notifications@github.com>
escreveu:

**Comment by LadyNaggaga** [comment]
Obrigado @nephew92   I am going file this a bug and we  will look into it.

**Comment by jonsequitur** [comment]
This looks like it was a momentary outage. @nephew92 are you still seeing the issue?

**Comment by LadyNaggaga** [comment]
Closing issue since we haven't heard back of recent occurrence of the above. @nephew92  please feel to let us know if this happens again.
