### ISSUE TITLE
The program didn't run

### ISSUE THREAD

**Issue by jslvstr** [dotnet/try#135]
Can't view the output for the program in c# which is Console.WriteLine("Hello World!");

**Comment by jonsequitur** [comment]
Thanks, @jslvstr. 

What is the URL where this occurred?

**Comment by Shivamckaushik** [comment]
Can't view the output for the program in c# which is Console.WriteLine("Hello World!");
URL-https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=3

**Comment by jonsequitur** [comment]
@Shivamckaushik Are you still seeing this issue? If so, what specific output are you seeing?

**Comment by LadyNaggaga** [comment]
Closing this issue. If you happen to see this bug again please don't hesitate to open a new one.
