### ISSUE TITLE
Can you please decompress this? 

### ISSUE THREAD

**Issue by zizuke** [dotnet/try#138]
https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings?tutorial-step=2

**Comment by LadyNaggaga** [comment]
adding @BillWagner  who owns the content.

**Comment by BillWagner** [comment]
@zizuke What do you mean by "decompress" this?

**Comment by duydevelopers** [comment]
> thêm @BillWagner , người sở hữu nội dung.

viec gi ma phu hop cho tat ca

**Comment by shanselman** [comment]
@duydevelopers Bạn cần giúp đỡ gì? Đây là nơi dành cho các lỗi. Không có sự trợ giúp của máy tính ở đây.
