### ISSUE TITLE
Bug report:.Net Editor - The service is temporarily unavailable. We are working on it.

### ISSUE THREAD

**Issue by bailiniuban** [dotnet/try#139]
write down these codes in dotnet editor and run it:
int a = 5 % 3;
Console.WriteLine(a);

Output:
The service is temporarily unavailable. We are working on it.

**Comment by bailiniuban** [comment]
but got right result in another example:
int a = 7;
int b = 4;
int c = 3;
int d = (a  + b) / c;
int e = (a + b) % c;
Console.WriteLine($"quotient: {d}");
Console.WriteLine($"remainder: {e}");

Output:
quotient: 3
remainder: 2

what's the matter...

**Comment by jonsequitur** [comment]
Due to busy traffic you may have been unable to get an execution agent. When this happens, some results are still available from our cache.
