### ISSUE TITLE
Typo on "Do More With Strings"

### ISSUE THREAD

**Issue by andreasottosson** [dotnet/try#14]
URL: https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-4

There is a typo in the code example in the first box.

"Console.WriteLine("[{trimmedMessage}]");" should be "Console.WriteLine($"[{trimmedMessage}]");"

**Comment by TyOverby** [comment]
@andreasottosson: thanks for the report!  The repo that hosts the content is over at github.com/dotnet/docs, but I've [submitted a PR with your recommended change](https://github.com/dotnet/docs/pull/3630).

**Comment by TyOverby** [comment]
Closing here; please track the PR that I opened.
