### ISSUE TITLE
Error in text in russian tutorial

### ISSUE THREAD

**Issue by kshmatov** [dotnet/try#140]
https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/list-collection?tutorial-step=3
Text:
> Если он имеет значение 1, элемент не найден

Correct version:
Если он имеет значение -1, элемент не найден

**Comment by LadyNaggaga** [comment]
@mairaw  where can we file this issue on docs.

**Comment by LadyNaggaga** [comment]
The docs team has been notified.  I am closing this issue here; please follow the issue over on the[ docs repo. ](https://github.com/MicrosoftDocs/feedback/issues/849)
