### ISSUE TITLE
Add lang attribute to <html> element

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/try#142]
Accessibility requires that html elements have the lang attribute set. At the moment, I think all button text etc. is in English right? So `<html lang="en">` is probably the right choice.

![image](https://user-images.githubusercontent.com/4741851/46498556-9b751000-c7d2-11e8-90cd-945803647865.png)

**Comment by LadyNaggaga** [comment]
@jonsequitur  can you please confirm that this issue is similar to the current Accessibility Compliance we opened  with the docs team https://github.com/dotnet/try/issues/119#ref-issue-366848733 ?

**Comment by jonsequitur** [comment]
This one is within the `iframe` and is therefore rendered by try.dot.net, so we can fix this one.

**Comment by rowanmiller** [comment]
Yep we had that same issue as #119 on our site too, fixed that one on our end.
