### ISSUE TITLE
Syntaxt Issue : Issue with Semicolon ( ; )

### ISSUE THREAD

**Issue by amitshaiwale** [dotnet/try#144]
When using Focus Mode on browser ( I'm using Chrome Browser ), and after writing Console.WriteLine("Hello World!"), I run this code and it executed successfully without throwing any error where it was supposed to throw an error for a **Semicolon ( ; )**

**Comment by jonsequitur** [comment]
Since this page uses C# scripting, an expression without a semicolon is allowed. This detail may change soon in Try .NET. For now though, it's expected.
