### ISSUE TITLE
Error in " String interpolation 

### ISSUE THREAD

**Issue by Sisco1987** [dotnet/try#145]
the code in this link don't work on visual studio 2017.
this is the link:
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=2

in v.s. 2017
![image](https://user-images.githubusercontent.com/44530199/47616693-8c773a00-dac0-11e8-9ab7-87572559c000.png)

i don't understand why, thank you.

**Comment by Sisco1987** [comment]
![image](https://user-images.githubusercontent.com/44530199/47613487-836e7480-da90-11e8-85d8-2a63e737e45e.png)

**Comment by Sisco1987** [comment]
![image](https://user-images.githubusercontent.com/44530199/47613500-be70a800-da90-11e8-957b-a9c344f55f35.png)

**Comment by svick** [comment]
I can see that you created this issue, but then deleted its contents. Do I understand it correctly that you did that, because you realized there isn't actually a problem here? If that's actually the case, then this issue should be closed.

**Comment by Sisco1987** [comment]
> I can see that you created this issue, but then deleted its contents. Do I understand it correctly that you did that, because you realized there isn't actually a problem here? If that's actually the case, then this issue should be closed.

yes.. i have some problem with this section. just a minute, please..

**Comment by svick** [comment]
The code in the example is a *script*. You can't directly paste it into a regular C# file, because you can't have a type inside a function.

You have to place the types outside the function and the statements inside it:

```c#
using System;

public class Vegetable
{
   public Vegetable(string name) => Name = name;

   public string Name { get; }

   public override string ToString() => Name;
}

public enum Unit { item, kilogram, gram, dozen };

class Program
{
    static void Main()
    {
        var item = new Vegetable("eggplant");
        var date = DateTime.Now;
        var price = 1.99m;
        var unit = Unit.item;
        Console.WriteLine($"On {date}, the price of {item} was {price} per {unit}.");
    }
}
```
