### ISSUE TITLE
Horizontal scrollbar looses mouse capture on mouse exit to the bottom

### ISSUE THREAD

**Issue by artemious7** [dotnet/try#146]
**Describe the bug**
In the browser code editor we have a horizontal scrollbar, which you can drag with a mouse. It looses mouse capture on mouse exit to the bottom of the scrollbar. Scrolling stops.

Steps:
- Mouse down on the scrollbar - mouse move to the left or to the right within the scrollbar - mouse up. It works.
- Mouse down on the scrollbar - mouse move to the outside of the scrollbar above it - mouse up. Scrolling still works.
- Mouse down on the scrollbar - mouse move to the outside of the scrollbar below it. Scrolling stops and I have to press on the scrollbar again. 

This is annoying. This scrolling behavior makes the editor inconvinient to use with a mouse - only touch or keyboard 👎 
And I don't see any button to enable wrapping, so that there was no horizontal scrolling - that would be very convinient. Or at least ability to make the editor wide enough.

**Where did this error occur?**
https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/tokens/interpolated

- microsoft.com/net/learn/dotnet/in-browser-tutorial - _the same problem here_
- try.dot.net - _here it works fine_

**What kind of error was it?**
- User Interface (UI)

**Screenshots**
![image](https://user-images.githubusercontent.com/16724889/47779193-3218ec00-dd01-11e8-8019-d5ccab43e090.png)

**Desktop:**
 - OS: Windows 10
 - Chrome; Edge
 - Version Chrome: 70.0.3538.77, Microsoft Edge 42.17134.1.0

**Smartphone:**
- not applicable

**Comment by LadyNaggaga** [comment]
Thank you for notifying us.  This issue is related to docs.microsoft.com so, I have open an new issue here so,they fix the bug. 
https://github.com/MicrosoftDocs/feedback/issues/848

**Comment by LadyNaggaga** [comment]
Closing issue. Please follow  the [issue here ](https://github.com/MicrosoftDocs/feedback/issues/848)
