### ISSUE TITLE
Doubles Large Number Error

### ISSUE THREAD

**Issue by regal60740** [dotnet/try#148]
**Describe the bug**
double third = 1000 / 3000;
Console.WriteLine(third);

This gives me 0 with your editor.

**Where did this error occur?**
- docs.microsoft.com
- microsoft.com/net/learn/dotnet/in-browser-tutorial
- [Noda Time](https://nodatime.org/2.3.x/userguide/recipes)
- try.dot.net - *Please note: this is our prodcution site*

**What kind of error was it?**
- Other : Wrong answer in editor.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser:  chrome
 - Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by svick** [comment]
That's actually the correct behavior. In C#, when you divide two integers, it performs *integer division*. That is, 1000 divided by 3000 is 0, remainder 1000. (If you want to access the remainder, you can use the `%` operator.) The resulting integer (0) is then converted to `double` to assign it to the `third` variable.

If you want to get (approximately) one third as the result, at least one of the two numbers will have to be a double. You can do that for example like this:

```c#
double third = 1000 / (double)3000;
Console.WriteLine(third);
```

This prints `0.333333333333333`.

**Comment by regal60740** [comment]
Thank you. When I add in a period with a zero, I get the right double
answer.
