### ISSUE TITLE
Control the formatting of interpolated expressions, DateTime.Now not correct.

### ISSUE THREAD

**Issue by regal60740** [dotnet/try#149]
**Describe the bug**
When I run this code, Date and time are incorrect on my machine. It is 11/12/18 a.m. and I'm getting October 2018 p.m.
**Where did this error occur?**

- microsoft.com/net/learn/dotnet/in-browser-tutorial

**What kind of error was it?**

- Other : date and time values incorrect.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser [chrome]
 - Version [70.0.3538.102 (Official Build) (64-bit)]

**Comment by jonsequitur** [comment]
You're seeing this because Try .NET currently caches past values if the code is identical to a submission we've seen before. If you make a small code change, you should see the correct date.

**Comment by LadyNaggaga** [comment]
For example in screenshot A  run this  DateTime.Now from [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) ref doc.
![cache](https://user-images.githubusercontent.com/2546640/48737681-b08bee00-ec1c-11e8-87fd-c887640eeabe.PNG)

Now, I made a small change and it gives the right time in timezone 
![fromagent](https://user-images.githubusercontent.com/2546640/48737721-cf8a8000-ec1c-11e8-8d39-2b036c28074e.PNG)

**Comment by LadyNaggaga** [comment]
You can also look at it in incognito mode in your browser and you will see the right time.

**Comment by jonsequitur** [comment]
@regal60740 The code change can also be a comment or whitespace.
