### ISSUE TITLE
when use <iframe>, shows error :Content Security Policy directive: "frame-ancestors 'none'".

### ISSUE THREAD

**Issue by wang498505194** [dotnet/try#158]
when I test the example in 
https://dotnet.microsoft.com/platform/try-dotnet?tdsourcetag=s_pctim_aiomsg

<iframe src="https://try.dot.net/?fromGist=df44833326fcc575e8169fccb9d41fc7">
</iframe>

it says:
Refused to display 'https://try.dot.net/?fromGist=df44833326fcc575e8169fccb9d41fc7' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

does it mean only private previous user can use it?
**then how can I use it?** thanks.

**Comment by jonsequitur** [comment]
Currently, you can only use Try .NET in approved host domains. We're hoping to lift this restriction soon.

**Comment by wang498505194** [comment]
Greatly appreciate your reply. Is there any way to apply for being an approved host domains?

**Comment by wang498505194** [comment]
or, can u tell me about when to open to other users?

**Comment by Kucashu** [comment]
It caused by CSP. U can try to set it.

**Comment by NikiforovAll** [comment]
Could you please tell me why this issue was closed? It doesn't look like it is clear what to do in case of embedding via iframe and what is on road map for that. Greatly appreciate your reply!
