### ISSUE TITLE
C# editor on beginner course is spastic

### ISSUE THREAD

**Issue by Haaviclar** [dotnet/try#16]
Sometimes works, sometimes doesn't. Sometimes allows entry and other times? Delete key on keyboard has not effect?

**Comment by jonsequitur** [comment]
@Haaviclar, can you provide a Iink to the page you’re seeing issues with and let us know which browser you're using?

**Comment by Chekroun** [comment]
I have the same problem, the link is : https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp#step-2

I'm on Firefox browser

**Comment by raven78** [comment]
Linux Mint 18.3 x64
FF - 57.0.1 (64-bit)
and this link https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp#step-3
Backspace does not delete content on the editor it goes back a page.
Copy button from code examples sometimes it copies sometimes not.
Paste is not in context menu.
Ctrl + A - select text of entire page not editor content
After hitting run it executes, shows result and "hangs?" You can't edit code and require refresh.

Google Chrome - Version 62.0.3202.94 (Official Build) (64-bit)
No UI problem just: 'The service is temporarily unavailable. We are working on it.' when you click Run

**Comment by jonsequitur** [comment]
This is the same issue as #17, which is specific to FireFox.

The service unavailable message was due to a momentary service issue which has resolved.

**Comment by DesktopMan** [comment]
Still failing on Chrome Version 63.0.3239.108 (Official Build) (64-bit) for me:

```
The service is temporarily unavailable. We are working on it.
` ``
