### ISSUE TITLE
I copy code from docs.microsoft.com but it run wrong!

### ISSUE THREAD

**Issue by hebiao1973** [dotnet/try#162]
https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=2

public class Vegetable
{
   public Vegetable(string name) => Name = name;

   public string Name { get; }

   public override string ToString() => Name;
}

public enum Unit { item, kilogram, gram, dozen };

var item = new Vegetable("eggplant");
var date = DateTime.Now;
var price = 1.99m;
var unit = Unit.item;
Console.WriteLine($"On {date}, the price of {item} was {price} per {unit}.");

run it ,but ……
(12,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(13,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(14,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(15,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(16,18): error CS1519: Invalid token '(' in class, struct, or interface member declaration
(16,19): error CS1031: Type expected
(16,19): error CS8124: Tuple must contain at least two elements.
(16,19): error CS1026: ) expected
(16,19): error CS1519: Invalid token '$"On {date}, the price of {item} was {price} per {unit}."' in class, struct, or interface member declaration

**Comment by mangokhan** [comment]
You forgot a brace. Try this:

public class Vegetable
{
public Vegetable(string name) => Name = name;

public string Name { get; }

public override string ToString() => Name;


public enum Unit { item, kilogram, gram, dozen };

var item = new Vegetable("eggplant");
var date = DateTime.Now;
var price = 1.99m;
var unit = Unit.item;
Console.WriteLine($"On {date}, the price of {item} was {price} per {unit}.");

}

**Comment by hebiao1973** [comment]
@mangokhan 
Thanks , I run your code in dotnet/try, but wrong too……

(15,18): error CS1519: Invalid token '(' in class, struct, or interface member declaration
(15,19): error CS1031: Type expected
(15,19): error CS8124: Tuple must contain at least two elements.
(15,19): error CS1026: ) expected
(15,19): error CS1519: Invalid token '$"On {date}, the price of {item} was {price} per {unit}."' in class, struct, or interface member declaration
(11,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(12,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(13,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(14,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code

**Comment by mangokhan** [comment]
Sorry I could not help. :(

**Comment by MattHelton** [comment]
I'm having the same issue.

**Comment by mangokhan** [comment]
Nothing wrong with the code itself.  It works fine here : 
https://dotnet.microsoft.com/platform/try-dotnet

**Comment by jonsequitur** [comment]
This is now fixed. The issue was specific to https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=2.
