### ISSUE TITLE
Focus Mode works with a properly set up browser. 

### ISSUE THREAD

**Issue by lblount79** [dotnet/try#163]
I tried using the focus on line training program with my default browser (which was not Microsoft Edge).  Once I switched to Microsoft Edge, the Focus system worked.  Obviously to use this tool, it needs a browser that is set up in a specific fashion.  And specifically not blocking all the "stuff" that other web sites use as an avenue for monitoring.  

If other web sites weren't inundating the on line experience with bastions of poorly acting garbage, it might be possible to use a Browser which has all the essential features "unblocked".

**Comment by jonsequitur** [comment]
Which browser were you using when you encountered a problem and what page did you see the issue on?

**Comment by lblount79** [comment]
Brave Browser with most of the cookies on "reject".    When I changed to Edge and allowed cookies, the Focus system worked appropriately.  I don't know if that was the reason but I met with success by enabling tracking and cookies via the Edge browser.
