### ISSUE TITLE
Interpolated Strings : include different data sample code doesn't workt

### ISSUE THREAD

**Issue by Petrando** [dotnet/try#164]
I copy and paste your sample code from[ this](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=2) link and run it, but it doesn't work. Perhaps the sample is outdated? 

Here are the error messages : 
(16,18): error CS1519: Invalid token '(' in class, struct, or interface member declaration
(16,19): error CS1031: Type expected
(16,19): error CS8124: Tuple must contain at least two elements.
(16,19): error CS1026: ) expected
(16,19): error CS1519: Invalid token '$"On {date}, the price of {item} was {price} per {unit}."' in class, struct, or interface member declaration
(12,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(13,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(14,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(15,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code

**Comment by Nakxion** [comment]
I had This problem I but it's now **FIXED**

**Comment by yaphets11** [comment]
have the same problem toooooooo

**Comment by mcxtlong** [comment]
+1

**Comment by jonsequitur** [comment]
This is now fixed.
