### ISSUE TITLE
c# tutorial issue 'new Dictionary'

### ISSUE THREAD

**Issue by fy8207345** [dotnet/try#169]
here is the link: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=4
var inventory = new Dictionary<string, int>()
  {
      ["hammer, ball pein"] = 18,
      ["hammer, cross pein"] = 5,
      ["screwdriver, Phillips #2"] = 14
  };

should be 
var inventory = new Dictionary<string, int>
  {
      ["hammer, ball pein"] = 18,
      ["hammer, cross pein"] = 5,
      ["screwdriver, Phillips #2"] = 14
  };

in asp.net core 2.2

**Comment by BillWagner** [comment]
@fy8207345 Both of those expressions are legal.

I'll close this.
