### ISSUE TITLE
Issues with `ref` local variables

### ISSUE THREAD

**Issue by BillWagner** [dotnet/try#173]
The following snippet does not compile in the https://try.dot.net browser:

```csharp
ref int Find(int[,] matrix, Func<int, bool> predicate)
{
    for (int i = 0; i < matrix.GetLength(0); i++)
        for (int j = 0; j < matrix.GetLength(1); j++)
            if (predicate(matrix[i, j]))
                return ref matrix[i, j];
    throw new InvalidOperationException("Not found");
}

int[,] sourceMatrix = new int[10, 10];
for (int x = 0; x < 10; x++)
    for (int y = 0; y < 10; y++)
        sourceMatrix[x, y] = x * 10 + y;

ref int item = ref Find(sourceMatrix, (val) => val == 42);
Console.WriteLine(item);
item = 24;
Console.WriteLine(sourceMatrix[4, 2]);
```
However, copying the `ref` return to a value does compile:

```csharp
ref int Find(int[,] matrix, Func<int, bool> predicate)
{
    for (int i = 0; i < matrix.GetLength(0); i++)
        for (int j = 0; j < matrix.GetLength(1); j++)
            if (predicate(matrix[i, j]))
                return ref matrix[i, j];
    throw new InvalidOperationException("Not found");
}

int[,] sourceMatrix = new int[10, 10];
for (int x = 0; x < 10; x++)
    for (int y = 0; y < 10; y++)
        sourceMatrix[x, y] = x * 10 + y;

int item = Find(sourceMatrix, (val) => val == 42);
Console.WriteLine(item);
item = 24;
Console.WriteLine(sourceMatrix[4, 2]);
```

Note the difference in the 4th line from the end of the sample.

**Comment by jonsequitur** [comment]
https://try.dot.net uses scripting, where this feature isn't supported. It works in these two cases:

https://try.dot.net?workspaceType=console
https://try.dot.net?workspaceType=blazor-console

**Comment by BillWagner** [comment]
Thanks @jonsequitur 

Adding @dendeli-msft 

It looks like I get the new experience by default *if* the program text represents a full program. I get the scripting behavior if I don't. Is that a correct analysis?

**Comment by jonsequitur** [comment]
Sorry, we don't detect whether the code represents a full program. 

We currently have specific pages configured for specific behaviors, and a couple of open issues (such as #174) where it's set wrong. 

@rchande

**Comment by BillWagner** [comment]
Ahh. What's the best way for me to work with you and your team to get a specific behavior on new content? 

This is new content, so I have no preferred solution. I want to minimize extra work for all in creating new experiences.

**Comment by jonsequitur** [comment]
In terms of which language features are supported, I'd suggest prototyping against https://try.dot.net?workspaceType=blazor-console. 

For scaffolding, for now assume you're executing inside `Main`. You'll be able to customize the scaffolding soon, which we should meet to discuss.
