### ISSUE TITLE
Difference in compiler behavior in try.net

### ISSUE THREAD

**Issue by BillWagner** [dotnet/try#175]
For this code snippet:

```csharp
object count = "5";

if (count is int number)
    Console.WriteLine(number);
else
    Console.WriteLine($"{number} is not an integer");
```

The try.net experience compiles and runs, with the message "0 is not an integer".

This is the incorrect behavior.  Try the same code locally, and you'll get `CS0165` "Use of unassigned local variable 'number'".

**Comment by colombod** [comment]
I get same error CS0165 in both online and compiled scenario
