### ISSUE TITLE
On create list the example didnt work on vs 2017

### ISSUE THREAD

**Issue by kkaramouzis** [dotnet/try#176]
var names = new List<string> { "<name>", "Ana", "Felipe" };
foreach (var name in names)
{
  Console.WriteLine($"Hello {name.ToUpper()}!");
}

//On the fist line I had to change List<string> with List<string>() to make it work on vs 2017

**Comment by svick** [comment]
> On the fist line I had to change `List<string>` with `List<string>()` to make it work on vs 2017

That can't be right. The code `var names = new List<string> { "<name>", "Ana", "Felipe" };` should work fine in VS 2017. What error did you get?

**Comment by SeriousMat** [comment]
Vs 2019, the example didn't work
I solved it adding this string at the top of the source:
using System.Collections.Generic;

> 
> 
> var names = new List { "", "Ana", "Felipe" };
> foreach (var name in names)
> {
> Console.WriteLine($"Hello {name.ToUpper()}!");
> }
> 
> //On the fist line I had to change List with List() to make it work on vs 2017
