### ISSUE TITLE
Typo on Main Page

### ISSUE THREAD

**Issue by briangithex** [dotnet/try#177]
**Describe the bug**
Contribute is spelled as "contrbiute."

**Where did this error occur?**
- try.dot.net - *Please note: this is our production site*
https://dotnet.microsoft.com/platform/try-dotnet

Get involved
Join us on GitHub to **contrbiute** ideas, report bugs, and help make Try .NET amazing.

**Comment by rowanmiller** [comment]
Fixed

**Comment by rowanmiller** [comment]
Many thanks for taking the time to report this.
