### ISSUE TITLE
Try.NET working well on mobile

### ISSUE THREAD

**Issue by dendeli-msft** [dotnet/try#178]
## Problem
Today, the .NET REPL is not mobile-friendly on docs, and can cause zoom/scaling/input issues when the content that integrates with it is opened from a mobile device.

## Proposed solution
Ensure that the mobile .NET REPL scales well and is able to accept user input in a standard way on mobile devices.

**Comment by LadyNaggaga** [comment]
This issue is out of scope for the .NET REPL and falls under Monaco editor being mobile friendly. 
https://github.com/Microsoft/monaco-editor/issues/246
