### ISSUE TITLE
Missing semi-colon fails to compile, but does not generate an error response

### ISSUE THREAD

**Issue by briangithex** [dotnet/try#180]
**Describe the bug**
Omitting a semi-colon causes console to claim to be compiling, rather than generating an error.  It never actually finished compiling.

**Where did this error occur?**
- try.dot.net - *Please note: this is our production site*
https://dotnet.microsoft.com/platform/try-dotnet

**What kind of error was it?**
- Other : Console claimed code was compiling, but it never actually compiled.

**How to Reproduce**

Input:
`string demo = "demo"`

Expected output:
> CS1002 ; expected

Actual output:
> Compiling in the cloud...

**Tested devices:**
Reproduced on Windows 10 with Both Edge 44.17763.1.0 and Chrome 74.0.3729.108

**Comment by jonsequitur** [comment]
@rowanmiller @rchande From what I can see, this affects https://dotnet.microsoft.com/platform/try-dotnet but not other locations. It's displaying compile errors coming from `/diagnostics` but not from `/compile`. This likely only became an issue when we switched to the Blazor-based implementation and I think it will require a fix in the script code at https://dotnet.microsoft.com/platform/try-dotnet.

**Comment by TheFinalDawn** [comment]
@jonsequitur Affects the Docs Tutorials too, can confirm.

**Comment by rowanmiller** [comment]
Agreed, this doesn't seem to be specific to dotnet.microsoft.com.
