### ISSUE TITLE
System.Object not defined or Imported (also Console is nonexistent

### ISSUE THREAD

**Issue by TheFinalDawn** [dotnet/try#181]
**Describe the bug**
When I try to type Console.WriteLine it gives me an error, pictured below. Yes it's possible to replicate it, I refreshed and caused it again by typing it manually.
(If it helps, I received errors CS0518 and CS0103, though it's in the picture)

**Where did this error occur?**
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/index

**What kind of error was it?**
System failure?

**Screenshots**
![ConsoleWrite](https://user-images.githubusercontent.com/45810243/56986283-3488c100-6b3f-11e9-9bb0-0f81aba47263.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Education)
 - Browser: Chrome
 - Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by jonsequitur** [comment]
Thanks, @TheFinalDawn. 

Which specific tutorial did you encounter this on? You linked to the index page, which doesn't contain any Try .NET editors.

**Comment by TheFinalDawn** [comment]
should work on all of them

**Comment by jonsequitur** [comment]
I'm not able to reproduce the problem but I might not be looking at the correct page. 

The editors on different pages are configured differently so issues like this will not necessarily be consistent across pages.

**Comment by TheFinalDawn** [comment]
Odd, It did it the first time but now I can't make it happen again... Must have been something I did on accident
