### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by johndotpage** [dotnet/try#182]
Typo on the website [front page](https://dotnet.microsoft.com/platform/try-dotnet).

Says "Try .NET is an embeddable code runner **the** enables you to..."

Should say "that" I assume.

![image](https://user-images.githubusercontent.com/50244516/57260342-0af9f900-705b-11e9-9f19-d6c0af6cad1d.png)

**Comment by JohnDotPage** [comment]
See also #177.

**Comment by spboyer** [comment]
@rowanmiller

**Comment by rowanmiller** [comment]
Fixed

**Comment by rowanmiller** [comment]
Thanks for pointing this out 👍
