### ISSUE TITLE
Typo on main page.

### ISSUE THREAD

**Issue by dhusemann** [dotnet/try#189]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3800677/57576964-38b3b900-7432-11e9-9182-718caedae7d5.png)
"you will need to" either needs to be "you will need to download" or "you will need the"

**Where did this error occur?**
github.com/dotnet/try

**What kind of error was it?**
Typo

**Comment by jonsequitur** [comment]
Thanks! Fixed.
