### ISSUE TITLE
Add namespaces needed for globalization

### ISSUE THREAD

**Issue by BillWagner** [dotnet/try#19]
As I add reference docs, I find that a couple additional namespaces should be imported for ease of use:

```csharp
using System.Threading; // For Thread.CurrentThread.CurrentCulture
using System.Globalization; // for lots of globalization types
```

**Comment by TyOverby** [comment]
These should all be available now.

**Comment by rpetrusha** [comment]
This issue should be reopened.

For instance, the example for the "C" standard numeric format string in [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-currency-c-format-specifier) is:
```
double value = 12345.6789;
Console.WriteLine(value.ToString("C", CultureInfo.CurrentCulture));
Console.WriteLine(value.ToString("C3", CultureInfo.CurrentCulture));
Console.WriteLine(value.ToString("C3", 
                  CultureInfo.CreateSpecificCulture("da-DK")));
```
This produces the following output:
```
(2,39): error CS0103: The name 'CultureInfo' does not exist in the current context
(3,40): error CS0103: The name 'CultureInfo' does not exist in the current context
(5,19): error CS0103: The name 'CultureInfo' does not exist in the current context
```
If the code is modified by fully qualifying references to CultureInfo, it works:
```
¤12,345.68
¤12,345.679
kr. 12.345,679
```
If it is wrapped in a complete type/method, an OutOfMemoryException results. For example, the following code:
```
public class Example
{
    public static void Main()
    {
        double value = 12345.6789;
        Console.WriteLine(value.ToString("C", System.Globalization.CultureInfo.CurrentCulture));
        Console.WriteLine(value.ToString("C3", System.Globalization.CultureInfo.CurrentCulture));
        Console.WriteLine(value.ToString("C3", 
                        System.Globalization.CultureInfo.CreateSpecificCulture("da-DK")));
    }
}
```
produces the following output:
System.OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) System.AppDomain.LoadAssemblyRaw(System.AppDomain,byte[],byte[],System.Security.Policy.Evidence,bool)
  at System.AppDomain.Load (System.Byte[] rawAssembly, System.Byte[] rawSymbolStore, System.Security.Policy.Evidence securityEvidence, System.Boolean refonly) <0x29da3b8 + 0x0003e> in <900ecd0f11284a0ca19b03bb59a43de7>:0 
  at System.AppDomain.Load (System.Byte[] rawAssembly, System.Byte[] rawSymbolStore, System.Security.Policy.Evidence securityEvidence) <0x29da258 + 0x00022> in <900ecd0f11284a0ca19b03bb59a43de7>:0 
  at System.AppDomain.Load (System.Byte[] rawAssembly) <0x29da188 + 0x00014> in <900ecd0f11284a0ca19b03bb59a43de7>:0 
  at System.Reflection.Assembly.Load (System.Byte[] rawAssembly) <0x29da0c0 + 0x00010> in <900ecd0f11284a0ca19b03bb59a43de7>:0 
  at MLS.WasmCodeRunner.CodeRunner.ProcessCompileResult (MLS.WasmCodeRunner.CompileResult compileResult, System.Int32 sequence) <0x29d85f8 + 0x00040> in <14b79e8017af40b2b2f7b42a1677165b>:0 
```
And adding a `using` statement to the previous code to import the System.Globalization namespace doesn't work:
```
(1,7): error CS1003: Syntax error, '(' expected
(1,7): error CS0118: 'System.Globalization' is a namespace but is used like a variable
(1,27): error CS1026: ) expected
(1,27): error CS0642: Possible mistaken empty statement
(1,1): error CS1513: } expected
```

**Comment by jonsequitur** [comment]
The difference in behavior between try.dot.net and docs.microsoft.com/dotnet is because the latter is using the in-browser execution model via Blazor, whereas the former is using C# scripting. We can opt specific pages (but not specific samples within a page) out of the Blazor implementation. This is a short-term fix because the scripting-based implementation will be going away. We should discuss how to adjust the content accordingly.

@rchande @jdanyow

**Comment by jonsequitur** [comment]
This issue is no longer relevant to the current implementation.
