### ISSUE TITLE
In .NET Core 2.1.602, running code samples breaks if there are spaces in the project path.

### ISSUE THREAD

**Issue by rlundy** [dotnet/try#195]
Environment:

Windows 10 x64
Chrome 74

Repro steps:

1. Create a folder.  In that folder, run `dotnet try demo` to create the samples.  (If they launch, hit Ctrl-C to exit out.)
1. Use `dotnet new globaljson` to create a global.json file.
1. Set the version in that global.json file to 2.1.602.
1. Use `dotnet try` to run the samples.
1. Click the run button on the first (Hello World) sample.

Result:

Unhandled Exception: No executable found matching command "dotnet-C:\Users\Ryan"

My user name has a space in it, and it looks like something in the demo project or the try tool is failing to account for spaces in the path.

(If I should try the samples with a different .NET Core SDK, please let me know.  This was the latest 2.1 version I had that wasn't a preview version.)

**Comment by LadyNaggaga** [comment]
@rlundy  I am unable to replicate this bug but, we will investigate this further. 
I too, have multiple versions of the .NET Core SDK on my machine. May ask you to try following these steps instead of trying these steps without trying to use global.json file ?  
https://github.com/dotnet/try/blob/master/Samples/Setup.md

**Comment by rlundy** [comment]
I've already tried running the samples by cloning the try repo and had no more luck with that than with `dotnet try demo`.

I'd be happy to try some other alternative if you have one.

**Comment by jonsequitur** [comment]
This is fixed. A new package will be available shortly.

**Comment by rlundy** [comment]
Confirmed working:

- Updated dotnet-try tool to 1.0.19266.1.
- Used `dotnet try demo` to create demo files in a folder.
- No global.json necessary.
- Samples in QuickStart.md run successfully; tested in Chrome and Vivaldi.

👍
