### ISSUE TITLE
when user code throws, the exception is not displayed in the output pane

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/try#2]
An exception thrown by successfully-compiling user code is not displayed in the output pane.

The exception is returned in the json response from the server. It appears to affect both try.dot.net/ide and docs.microsoft.com.

**Comment by piotrpMSFT** [comment]
I have a PR out for a fix. The Exception message is appended to the output using the same formatting as is done for console. Specifically:

```
any
stdout
content

Unhandled Exception: exception
    at details
```

**Comment by piotrpMSFT** [comment]
Fixed.

**Comment by EisenbergEffect** [comment]
Sweet!!! @piotrpMSFT Do we need to make any updates in the docs front-end code?
