### ISSUE TITLE
Include `System.Threading.Tasks` to the standard namespaces

### ISSUE THREAD

**Issue by BillWagner** [dotnet/try#22]
It's not convenient to create samples that use modern TAP based async work because the `System.Threading.Tasks` namespace is not included by default. That could lead people to use older APIs instead of the async and await based protocol.

I had a conversation on email about this with @TheRealPiotrP that this change would make the default interactive experience different than the local experience for Visual Studio or dotnet CLI users. Should this concept be expanded to update the default list of imported namespaces in the C# templates for Visual Studio and `dotnet new`.  /cc @KathleenDollard @Pilchie

**Comment by jonsequitur** [comment]
@rchande

**Comment by TyOverby** [comment]
I think this issue has been fixed?  At the very least, I can use tasks in the editor.

```c#
using System.Threading.Tasks;

var t = Task.FromResult(5);
Console.WriteLine(await t);
```

**Comment by TyOverby** [comment]
Closing for now.  If I'm misunderstanding this issue @BillWagner, please reopen.

**Comment by BillWagner** [comment]
@TyOverby This works perfectly for the try.dot.net experience.

I'd like to have similar functionality for the [docs.microsoft.com quickstart](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-1) experience.

/cc @TheRealPiotrP  @LadyNaggaga Is there a different location for this feature request?

**Comment by TyOverby** [comment]
@BillWagner It appears to work perfectly on the link that you gave me.

![image](https://user-images.githubusercontent.com/573215/34751318-c81bccec-f560-11e7-869b-03474ea1d5a4.png)

I get autocomplete and everything.
