### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by najish** [dotnet/try#222]
issue is here should change only one character which is d instead of e . for intellisence

https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=3

in the first block of tips there is a mis character kindly change it . thank you

**Comment by jonsequitur** [comment]
@BillWagner

**Comment by BillWagner** [comment]
@najish The current text is correct. If you type a `.` after the last letter in a variable, the editor provides a list of possible methods you can use.  See the following image:

<img width="331" alt="intellisense" src="https://user-images.githubusercontent.com/493969/59204391-86752b80-8b6e-11e9-802d-79dea7b5a7b9.png">

What should we add to that note to make this more clear?

**Comment by BillWagner** [comment]
closing due to lack of a response.
