### ISSUE TITLE
Markdown Formatting looks to be broken on Getting Started Guide

### ISSUE THREAD

**Issue by jwendl** [dotnet/try#23]
Going to the getting started guide for .NET it looks like the markdown isn't being formatted and I have an empty "Run" box to the right.

![image](https://user-images.githubusercontent.com/1068431/33916925-41761730-df60-11e7-8a72-e447e2384f7d.png)

**Comment by jonsequitur** [comment]
@BillWagner 

It looks like the content is being escaped rather than treated as MarkDown.

**Comment by BillWagner** [comment]
The site engineering team made a breaking change to the tutorials parser.

This is fixed in /dotnet/docs#3923  It should go live tomorrow.

**Comment by BillWagner** [comment]
@jwendl I just looked at the live site, and this appears fixed to me. I'll close the issue.  Please let us know if you see it again.

**Comment by jwendl** [comment]
Looks perfect - thank you for fixing it 👍
