### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by jimbobbennett** [dotnet/try#262]
#### Describe the bug
Create markdown referencing a local image file.
The image is not found.

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [X] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
<img width="1052" alt="2019-06-07_17-46-38" src="https://user-images.githubusercontent.com/1710385/59120042-4cc4da80-894c-11e9-9768-5886684f32e1.png">

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [X] Safari

**Comment by jimbobbennett** [comment]
@akshita31 - will your changes in #268 also allow css and js files to be referenced?

**Comment by akshita31** [comment]
@jimbobbennett Yes javascript and css will also work as we are using the Static file handler from Asp.net. I have added a test in the PR that checks if a javascript file can be served.
