### ISSUE TITLE
Type Casting Error  (decimal)Math.PI 

### ISSUE THREAD

**Issue by AliAdil** [dotnet/try#27]
double radius = 2.50;
double area = Math.PI * radius * radius;
Console.WriteLine(area);

This error occurred when I want to solve problem in decimal  "error CS0019: Operator '*' cannot be applied to operands of type 'decimal' and 'double"

decimal radius = 2.50M;
decimal area = (decimal)Math.PI * radius * radius;
Console.WriteLine(area);

**Comment by TyOverby** [comment]
This repo is for the try.dot.net website and integrations in other sites (like Docs).  It sounds like you are having trouble understanding C# language rules.  Please check out the c# language gitter channel https://gitter.im/dotnet/community
