### ISSUE TITLE
Enable linking code to try.dot.net website

### ISSUE THREAD

**Issue by HermanEldering** [dotnet/try#278]
I would like to share a link to https://try.dot.net/ such that it runs the source code that I specify.

It could work like .NET Fiddle which has a button that provides a link with a short key to the current source code. Alternatively, and this might be nicer, is to allow specifying a gist.github.com link with the source code.

**Comment by jonsequitur** [comment]
You can do this today with a gist: https://try.dot.net/?fromGist=ef0cea23e938396193106254548e6261.

This is currently a somewhat limited experience though because you can't control which assemblies are referenced.

Related: #217

**Comment by HermanEldering** [comment]
Nice! Kinda stupid that I didn't notice it being mentioned on https://dotnet.microsoft.com/platform/try-dotnet several times. When I skimmed over that page it didn't seem to contain anything useful...
