### ISSUE TITLE
Path.GetFileName returns incorrect value

### ISSUE THREAD

**Issue by pbojanczyk** [dotnet/try#279]
#### Describe the bug
Add using System.IO; to your using statements and paste the following line:
`Console.WriteLine(System.IO.Path.GetFileName(@"c:\program files\test.png"));`

Expected Result:
test.png

Actual Result:
c:\program files\test.png

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: printed value was incorrect

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
The file APIs in WebAssembly use *nix-style paths, independent of your actual OS. If you do this you'll get the expected result:

```cs
Console.WriteLine(System.IO.Path.GetFileName(@"/program files/test.png"));
```
