### ISSUE TITLE
Chrome: Editor is unresponsive to highlighting after first action

### ISSUE THREAD

**Issue by ryanmendoza** [dotnet/try#29]
Selecting text does not work in Chrome 63.0.3239.132 (macOS) after you do it once. 

Repro steps:

- Highlight a line of text in web editor
- Change focus from highlighted line (to another area in text editor or outside of the editor scope, doesn't make a difference)
- Not able to highlight another line of text or cursor actions begin to behave sporadically in editor

**Comment by TyOverby** [comment]
@ryanmendoza: Which page are you viewing this behavior in?

**Comment by ryanmendoza** [comment]
@TyOverby https://www.microsoft.com/net/learn/in-browser-tutorial/1

**Comment by LadyNaggaga** [comment]
@ryanmendoza  at the time of this issue dot.net was not using the Try .NET online REPL.  So, I am closing this issue. If you see this behavior again please do let use know.
