### ISSUE TITLE
Potential lead for #290

### ISSUE THREAD

**Issue by Entroper** [dotnet/try#294]
Hi, I saw your issue #290 and recall running into a problem with `Math.Round` in my Blazor project.  Thought I would direct you to the issue and resolution to see if it might help you:

https://github.com/aspnet/Blazor/issues/1661

**Comment by LadyNaggaga** [comment]
@Entroper  Thank you so much for bringing this to our attention. We currently working on fixing this bug.

**Comment by akshita31** [comment]
@Entroper Thank you for pointing this out. We have updated the version of blazor and its fixed now :)
