### ISSUE TITLE
Opening editor takes hell lot of time and makes lose interest in trying

### ISSUE THREAD

**Issue by sateeshmachineni** [dotnet/try#3]
This shouldn't take this much time(more than 1 minute at minimum) and copy doesn't work reliably..These kind of issues makes people don't try this even after improved iterations

**Comment by LadyNaggaga** [comment]
@sateeshmachineni  to better fix your issue could please us know:

-  what browser you are using ?

-  Where are you accessing the Try .NET from try.dot.net or docs.microsoft.com ?
