### ISSUE TITLE
Default code snippet has inconsistent brace placement

### ISSUE THREAD

**Issue by jaredpar** [dotnet/try#30]
The initial code snippet uses `{` both on the same line and on a separate line. Feel like it should be consistent here. 

Full snippet: 

``` c#
using System;
using System.Linq;

public class Program
{
  public static void Main()
  {
    // !!! NEW LINE !!!
    foreach (var i in Fibonacci().Take(20))
    {
      Console.WriteLine(i);
    }
  }

  private static IEnumerable<int> Fibonacci()
  {
    int current = 1, next = 1;

    // !!! SAME LINE !!!
    while (true) {
      yield return current;
      next = current + (current = next);
    }
  }
}

```
  
**EDIT** Url is https://try.dot.net/

**Comment by BillWagner** [comment]
@jaredpar What page did you see this?  I looked at the source for the quick starts on docs.microsoft.com and I can't find it anywhere.

**Comment by terrajobst** [comment]
I see it right here: 
![image](https://user-images.githubusercontent.com/5169960/34748661-79d4211e-f552-11e7-8d04-e23fb0bbba77.png)

**Comment by jaredpar** [comment]
@BillWagner @terrajobst has the right URL. It is what I see when I got to https://try.dot.net/

**Comment by jonsequitur** [comment]
It's consistent now.
