### ISSUE TITLE
Defining a function in one cell and calling it in another results in compilation error

### ISSUE THREAD

**Issue by eerhardt** [dotnet/try#345]
#### Describe the bug
See the screen shot below.

I created a notebook, imported an assembly, defined a function that took a parameter of a type from that assembly in a cell. When I tried invoking the function in another cell I got a compilation error:

```
(2,6): error CS1503: Argument 1: cannot convert from 'Microsoft.ML.IDataView [/Users/eerhardt/.nuget/packages/microsoft.ml.dataview/1.2.0/lib/netstandard2.0/Microsoft.ML.DataView.dll]' to 'Microsoft.ML.IDataView [Microsoft.ML.DataView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]'
```

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
<img width="1145" alt="Screen Shot 2019-07-25 at 2 10 52 PM" src="https://user-images.githubusercontent.com/8291187/61901938-8e9ee580-aee6-11e9-8b19-eba46d7f959a.png">

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by pgovind** [comment]
I just ran into this too. Here's what I was trying to do:

<img width="852" alt="Bug" src="https://user-images.githubusercontent.com/10480119/63123730-832b6100-bf5e-11e9-9022-c753b7af6e87.PNG">

**Comment by svick** [comment]
I suspect this is the same issue as https://github.com/dotnet/roslyn/issues/23123.

**Comment by eerhardt** [comment]
I believe we are going to need a fix for this issue before the notebook experience is a viable option for customers. Without this being fixed I can't imagine getting any real work done in a C# notebook.
