### ISSUE TITLE
Verify and run errors because --region and -- source-file switches are case sensitive 

### ISSUE THREAD

**Issue by WaltRitscher** [dotnet/try#352]
#### Describe the bug
It appears that the parser for --verify and --source-file is case sensitive.  Here are the issues I am seeing.

**--source-file**
On Windows PC and Mac OS name casing is not used for file name differentiation. However, using the incorrect case name in the C# code fence causes errors.  
### Working Example
![propercaseFilename](https://user-images.githubusercontent.com/6786189/62253848-16d02f80-b3ac-11e9-86ee-4610d12cd10b.png)
### Error Example
![lowercaseFilename](https://user-images.githubusercontent.com/6786189/62254001-821a0180-b3ac-11e9-9de8-aaaef7dea724.png)
![lowercaseFilenameVerify](https://user-images.githubusercontent.com/6786189/62254015-86461f00-b3ac-11e9-98cb-8b5585e6b537.png)
![lowercaseFilenameRunError](https://user-images.githubusercontent.com/6786189/62254019-88a87900-b3ac-11e9-8c68-6747cb9936fd.png)

**Preferred Fix**

Change behavior to use case insensitive **--source-file** switch.

---
**--region**
C# files can have multiple #regions with the same name; with same case or different case.  The verify tool correctly flags the attempt to have code with two identical matching case #region names.  But it is case sensitive, so it is possible to have two regions that vary only by case.  In this scenario, passing the wronged cased region in the code fence causes a verification error. 
**Preferred Fix.**  
Allow case-insensitive **–region** names in the code fence.  Flag any duplicates(regardless of case) during verify process.

---
#### Did this error occur while using `dotnet try` or online?
- [ x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ x] Other:

#### Please complete the following:
 - OS
    - [ x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x ] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
This is intentional because we want the content to be portable to Linux machines as well.

**Comment by WaltRitscher** [comment]
Okay, I can see why you'd  need that for Linux.  How about a better error message for when this happens because of a case name error?  The "namespace already contains..." message doesn't help narrow down what is the error.
