### ISSUE TITLE
Try.NET Async/Await throws exceptions

### ISSUE THREAD

**Issue by Psimatrix** [dotnet/try#362]
#### Describe the bug
When I try to execute code that is awaitable, Try.net throws and exception. The exception is not shown in the output due to other previously reported bugs but application stops working.

Below I have some code that is attempting to do basic httpClient authentication. I show the before and after code changes. The console.writeline() are never reached when running as an example piece of code in Try.NET. Once I changed to second version of the code the console.writelines were reached. My guess is this is similar in other Async/Await siuations.

*****************************
With Async/Await
static async Task<HttpClient> GetHttpClient(HttpClientParams clientParams)
{	
	var httpClient = new HttpClient();
	var disco = await httpClient.GetDiscoveryDocumentAsync(clientParams.AuthorityUrl);
	Console.WriteLine("here 1");
	if (disco.IsError) throw new Exception(disco.Error);

	var tokenResponse = await httpClient.RequestPasswordTokenAsync(new PasswordTokenRequest()
	{
		Address = disco.TokenEndpoint,
		ClientId = clientParams.ClientId,
		ClientSecret = clientParams.ClientSecret,
		UserName = clientParams.OperatorId,
		Password = clientParams.OperatorPw,
		Scope = "offline_access"
	});	
	Console.WriteLine("here 2");
	if (tokenResponse.IsError) throw new Exception(tokenResponse.Error);
	httpClient.SetBearerToken(tokenResponse.AccessToken);	
	return httpClient;
}
*************************************
Without Async/Await

 static HttpClient GetHttpClient(HttpClientParams clientParams)
        {
            try
            {
                var httpClient = new HttpClient();
                var disco = httpClient.GetDiscoveryDocumentAsync(clientParams.AuthorityUrl).Result;
                Console.WriteLine("here 1");
                if(disco.IsError) throw new Exception(disco.Error);

                var tokenResponse = httpClient.RequestPasswordTokenAsync(new PasswordTokenRequest()
                {
                    Address = disco.TokenEndpoint,
                    ClientId = clientParams.ClientId,
                    ClientSecret = clientParams.ClientSecret,
                    UserName = clientParams.OperatorId,
                    Password = clientParams.OperatorPw,
                    Scope = "offline_access"
                }).Result;
                Console.WriteLine("here 2");
                if (tokenResponse.IsError) throw new Exception(tokenResponse.Error);
                httpClient.SetBearerToken(tokenResponse.AccessToken);
                return httpClient;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

#### Did this error occur while using `dotnet try` or online?
- [x ] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x ] Other:

#### Please complete the following:
 - OS
    - [x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x ] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Thanks, @Psimatrix. You may be able to see more information about the exception in your console by running in verbose mode:

```console
> dotnet try --verbose
```

> The exception is not shown in the output due to other previously reported bugs but application stops working.

Is there a specific issue that you think might be related?
