### ISSUE TITLE
The 'Create Lists' tutorial doesn't specify import

### ISSUE THREAD

**Issue by google-mac** [dotnet/try#371]
When going through the [Create Lists](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=1) tutorial, my code would not run until I added `using System.Collections.Generic` to the top of my file. This was not specified in the tutorial.

This error occurred in my own development environment on macOS (not online).

**Comment by jonsequitur** [comment]
@BillWagner

**Comment by BillWagner** [comment]
Issue moved to [dotnet/docs #13939](https://github.com/dotnet/docs/issues/13939) via [**ZenHub**](https://www.zenhub.com/)
