### ISSUE TITLE
"Enter focus mode" does not work

### ISSUE THREAD

**Issue by zhenisduissekov** [dotnet/try#372]
#### Describe the bug
At https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=5 I am trying to open "FOCUS MODE" but after opening it shows this message: The service is temporarily unavailable. We are working on it.

#### Did this error occur while using `dotnet try` or online?
- [ X] `dotnet-try`
- [ X] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ X] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![Снимок экрана 2019-08-14 в 11 32 14](https://user-images.githubusercontent.com/52789114/62996631-332d9b00-be87-11e9-9197-81d93270440d.png)

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [ X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X ] Chrome
    - [ ] Edge
    - [ X] Safari

**Comment by LadyNaggaga** [comment]
@zhenisduissekov  I am unable to reproduce your error in Chrome on a PC.  Can you please us know if it still occurring

**Comment by zhenisduissekov** [comment]
Hello LadyNaggaga,

No worries, i think it does not matter

с уважением

Женис Дуйсеков
zduissekov@gmail.com



> 14 авг. 2019 г., в 22:52, LadyNaggaga <notifications@github.com> написал(а):
> 
> u please us know if it still occurring
