### ISSUE TITLE
Android on screen function is not working, back space can't be used to edit

### ISSUE THREAD

**Issue by hmanxx** [dotnet/try#429]
#### Describe the bug
Please provide as much information as you can.

#### Did this error occur while using `dotnet try` or online?

- [ ] online

#### What kind of error was it?

- [ ] Other:
When using the trying example on .net c# learning tutorial to edit the code, 
Onscreen keyboard, Google GBOARD miss the following
1- backspace key is not deleting characters.
2. Copy and paste context menu , activating copy and paste menu,it is flashing and not staying on screen, can't do copy and paste

While typing on this GitHub feedback window, keyboard is fully functional, not above reported bugs 

#### Screenshots
Can't capture 
.

#### Please complete the following:
 - OS

    - [ ] Android
 - Browser 
    - [ ] Chrome

**Comment by terrimorton** [comment]
These issues were resolved with the June 2024 try.net update.
