### ISSUE TITLE
code is not editable

### ISSUE THREAD

**Issue by sudhir512kj** [dotnet/try#45]
Once i run a code in editor it runs...but after that when i need to run other code old code doesn't edit

**Comment by jonsequitur** [comment]
Thanks, @sudhir512kj. What browser were you using and which URL were you visiting?

**Comment by sudhir512kj** [comment]
I am using Mozilla Firefox latest version in ubuntu 16.04 .. i was trying .net on browser

**Comment by sudhir512kj** [comment]
@jonsequitur did you get my problem and its solution

**Comment by jonsequitur** [comment]
This looks like the same issue as #17.

**Comment by sudhir512kj** [comment]
@jonsequitur

**Comment by sudhir512kj** [comment]
yes i think you are right... @jonsequitur that looks same like this issue...so what is the solution for this
