### ISSUE TITLE
Support wildcards in NuGet Versions

### ISSUE THREAD

**Issue by eerhardt** [dotnet/try#458]
#### Describe the bug
Please provide as much information as you can.

Try the following in a notebook:

```
#r "nuget:Microsoft.ML,1.*"
```

## Expected result
I expect to get the latest stable ML.NET package.

## Actual result
```
Attempting to install package Microsoft.ML, version 1....done!
Failed to add reference to package Microsoft.ML

index | value
-- | --
0 | error: '1.' is not a valid version string.

```

## Note

If I do the following in a .csproj, it works correctly:

```xml
    <PackageReference Include="Microsoft.ML" Version="1.*" />
```

I expect it to work the same in a notebook.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

/cc @rchande

**Comment by tebeco** [comment]
@eerhardt as a workaround waiting for the fix can you try hacking around with brackets to see if it works ?
like this from the version latest :
`Version="[*,9999.0]"`
if it works then i'm curious if `[*, 2.0)` if you don't want major bump

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/68503890-beb19080-0218-11ea-8700-f90607e1e211.png)
