### ISSUE TITLE
Site is not crawler friendly

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/try#46]
No description when I search for "try dot net" in Bing. Which will put some folks off trying it.

![image](https://user-images.githubusercontent.com/6385855/36006802-dea29900-0cf3-11e8-87f1-bd826a6b9da9.png)

Google the same

![image](https://user-images.githubusercontent.com/6385855/36006847-3466242e-0cf4-11e8-9f93-1edb8a53df0d.png)

I assume this is because of https://try.dot.net/robots.txt blanket disallow:
```
User-agent: *
Disallow: /
```

Perhaps there's a way to "Allow" some file that the search engines would use for a description: or possibly you could just stop disallowing them?

**Comment by LadyNaggaga** [comment]
The site is actively being worked on and I will fix this.  Thanks for brining it to my attention.

**Comment by TheRealPiotrP** [comment]
Thanks @danmosemsft! The TDN home page is not yet super user friendly, so we're not actively driving traffic to it yet. Most of our users today access TDN through partner sites like docs.microsoft.com. We'll be improving discoverability as the home page's purpose becomes more obvious over coming sprints :)

**Comment by danmosemsft** [comment]
Still not fixed -- is it worth trying a few cheap experiments with edits to the robots.txt? I appreciate your point that you are still working on the homepage, but it seems a pity to put off folks searching.

**Comment by LadyNaggaga** [comment]
We have a new homepage https://www.microsoft.com/net/platform/try-dotnet  hopefully this will solve this soon.

**Comment by jonsequitur** [comment]
The current landing page wasn't entirely intended to be the landing page for search results. Along the with new homepage, the fix for this is on its way to production: https://github.com/dotnet/try/issues/147.
