### ISSUE TITLE
Parse errors in directives doesnt show up

### ISSUE THREAD

**Issue by akshita31** [dotnet/try#469]
Steps to Reproduce:

In a notebook execute the following: 
![image](https://user-images.githubusercontent.com/12554141/65289152-6e626000-dafe-11e9-9e82-5d7f652d8bc3.png)

Expected behavior:
It should show some sort of Parse Error saying that lsmagic doesnt take any argument 

Actual Behavior:
If there is a parse error during parsing the directives, the command is passed to the Kernel which displays confusing error:

https://github.com/dotnet/try/blob/91ff6e81150397499a8d215bd80cdab18192a5c7/Microsoft.DotNet.Interactive/KernelBase.cs#L179

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/68517697-73f63f80-023d-11ea-96d1-ddc483ff52d4.png)
