### ISSUE TITLE
System.IO.FileNotFoundException when open C# notebook in Jupyter

### ISSUE THREAD

**Issue by bhrnjica** [dotnet/try#498]
I have started to test C# Jupyter Notebook after I followed the instruction how to install Jupyter .NET Kernel on my local machine.
I have successfully installed the latest version of Anaconda with Python 3.7. Once the Anaconda installed , I opened Anacoda CMD prompt and installed 'dotnet try’ tool from the instruction document.

Everything was installed without any errors. I have opened Jupyter Notebook and tried to open 
MLNET-Jupyter-Demo.ipynb predefined sample. As soon I run the first cell in the notebook, the .NET kernel throws the exception in the cmd:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Components.Prerendering
, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
Before and after the bug appeared, I could successfully run Python Notebook.

I attached the full exception in the bug report.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

#### Please complete the following:
 - OS
    - [x] Windows 10 and Windows Server 2019 Datacenter
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome and Microsoft Edge Beta , Firefox
    - [ ] Edge
    - [ ] Safari

[NETKernel Exception.txt](https://github.com/dotnet/try/files/3692549/NETKernel.Exception.txt)

**Comment by jonsequitur** [comment]
Thanks, @bhrnjica. Can you also provide the output of the following two command lines:

```console
> dotnet --info
> dotnet-try --version
```

**Comment by bhrnjica** [comment]
Sure, here are screenshots with the commands:
![2019-10-05_9-14-43](https://user-images.githubusercontent.com/1240016/66251515-29226d00-e751-11e9-8b16-700795a37925.png)
![2019-10-05_9-15-38](https://user-images.githubusercontent.com/1240016/66251517-2c1d5d80-e751-11e9-8198-845298c338ad.png)

**Comment by bhrnjica** [comment]
After update to the latest version of ‘dotnet try’ tool ```(1.0.19507.38+911bbcb1cbe963268623f95b76cad450006be78b)```, everything works perfectly.
