### ISSUE TITLE
Unable to find package Microsoft.Data.DataFrame

### ISSUE THREAD

**Issue by jwood803** [dotnet/try#499]
#### Describe the bug
Downloaded the sample notebooks and ran them in my local Jupyter Lab. Attempted to run `#r "nuget:Microsoft.Data.DataFrame,0.1.1-e190920-1"` and attempted to run without the version and got the below error. 

```
Failed to add reference to package Microsoft.Data.DataFrame

error: Unable to find package Microsoft.Data.DataFrame. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, ML.NET Daily, nuget.org
```

Probably an issue with my set up but wanted to report it just in case.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [x] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
This package isn't available yet on nuget.org but you can get it by adding the following to your global nuget.config under `configuration/packageSources`:

```xml
<add key="corefxlab" value="https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json" />
```

**Comment by jwood803** [comment]
Thanks @jonsequitur! That was what I needed to run the sample :)

**Comment by rfrerebe** [comment]
I found you can add this instead of modifying your global settings
```
#r "nuget:bl=true"
#r "nuget:RestoreSources=https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json"
#r "nuget:Microsoft.ML,version=1.4.0-preview"
#r "nuget:Microsoft.ML.AutoML"
#r "nuget:Microsoft.Data.DataFrame,version=0.1.1-e191008-1"
```

**Comment by worthy7** [comment]
Tried the solution @rfrerebe  wrote.

```
Installing package bl.....done!
Failed to add reference to package bl
...
Installing package RestoreSources.....done!
Failed to add reference to package RestoreSources
```

**Comment by rfrerebe** [comment]
Get new version from https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/Microsoft.Data.DataFrame
Hopefully at some point it will be on https://nuget.org
