### ISSUE TITLE
Code Modification

### ISSUE THREAD

**Issue by octacorewt** [dotnet/try#50]
There is a problem after running the code, if you want to modify the code e.g add or remove code, you cant write anything, its blocked, the only way to activate the code editor is by right clicking and and cut, that activates code editor to keep adding or removing code. So might want to fix that.

**Comment by LadyNaggaga** [comment]
Are you using Try .NET on the [homepage](https://try.dot.net/) or on[ docs](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world)? Could you please give more information on that and what browser you are using?

**Comment by iodaynamics** [comment]
Hi, I’m using Mozilla quantum, and yes using the .NET editor. I haven’t tried any other web browser.

**Comment by jonsequitur** [comment]
This sounds like the same issue as #17.

**Comment by TheRealPiotrP** [comment]
@rowanmiller it looks like the alternative implementation on dot.net is continuing to create unnecessary confusion. I hope that site can take advantage of the unblocking features implemented in try.dot.net soon so folks have a consistent experience.

**Comment by iodaynamics** [comment]
Yes, exactly like #17, after running the code the editor doesn’t accept code typing, it’s like if it is blocked, what I do to unblock the editor is I right click an select Cut, this some how reactivares the editor. Again I haven’t tried with another web browser, it might work differently.
