### ISSUE TITLE
Erroneous error message

### ISSUE THREAD

**Issue by ga69russ** [dotnet/try#53]
I entered code on the Numbers Challenge page and the '*' between the two 'radius' variables was flagged by the error indicator. The message indicated that the operator was not valid between a double and a decimal. The variable was declared as double.

I could not include my code as it was erased before I could copy it.

**Comment by BillWagner** [comment]
Thanks for writing this @ga69russ 
The application works correctly. You just ran into one of the trickier rules in C#. It's a bit advanced, so I didn't cover it in this tutorial.

The `double` type and the `decimal` type have different ranges and different precision. For that reason, the language doesn't automatically convert between those types. If you work through the sample and use the `double` type for all the variables, you should be fine.

**Comment by BillWagner** [comment]
Closing by moving to dotnet/docs#4466
