### ISSUE TITLE
.Net Codes arent working

### ISSUE THREAD

**Issue by tropius12** [dotnet/try#56]
Hello Guys, maybe somebody can help me here.
i am trying to solve the tutorials from the .net site (they are pretty good).
.Net is giving you codes to run on a browser (i am using Microsoft Visual Studio). They wrote this code:

var inventory = new Dictionary<string, int>();
  inventory.Add("hammer, ball pein", 18);
  inventory.Add("hammer, cross pein", 5);
  inventory.Add("screwdriver, Phillips #2", 14);

  Console.WriteLine($"Inventory on {DateTime.Now:d}");
  Console.WriteLine(" ");
  Console.WriteLine($"{"Item",-25}    {"Quantity",10}");
  Console.WriteLine(" "); 
  foreach (var item in inventory)
     Console.WriteLine($"{item.Key,-25}     {item.Value,10}");

And this code is not working, dont know why. It has 67 issues (says Visual Studio). So maybe someone here can help me ? I would appreciate if i could do the whole tutorial.

Greetings
Tropius

**Comment by svick** [comment]
The most likely reason is that you're pasting your code directly into Program.cs. But if you're writing C# code in Visual Studio, you're using "regular" C#, not the special "scripting" variant used by Try.NET.

With regular C#, you have to put your code into a `Main` method in some class and you also have to specify the namespaces that you're using. Try:

```c#
using System;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        var inventory = new Dictionary<string, int>();
        inventory.Add("hammer, ball pein", 18);
        inventory.Add("hammer, cross pein", 5);
        inventory.Add("screwdriver, Phillips #2", 14);

        Console.WriteLine($"Inventory on {DateTime.Now:d}");
        Console.WriteLine(" ");
        Console.WriteLine($"{"Item",-25} {"Quantity",10}");
        Console.WriteLine(" ");
        foreach (var item in inventory)
            Console.WriteLine($"{item.Key,-25} {item.Value,10}");
    }
}
```

**Comment by tropius12** [comment]
Ah, thank you then! It's working now.

**Comment by jonsequitur** [comment]
Thanks for the update @tropius12  and thanks for the help @svick.
