### ISSUE TITLE
Test with assertion on timing feels odd

### ISSUE THREAD

**Issue by cartermp** [dotnet/try#574]
This assertion doesn't seem right to me:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/6309070/67814694-f161c900-fa61-11e9-9855-ee6ac8cf14dc.png">

This failed in our CI on a change to a notebook example, so the change didn't affect this test. Given that we don't have control over the pools that CI runs on, these sorts of intermittent failures seem like they'll slow us down over time.

**Comment by colombod** [comment]
The time gap in this case is what we test for, that means we get the 2 events apart and not as a single stream. The test was introduce to make sure async output it is presented asynchronously and not as a blast of events

**Comment by colombod** [comment]
The test should check order and timing is only relevant with timestamped events
