### ISSUE TITLE
try in docker container

### ISSUE THREAD

**Issue by ignatandrei** [dotnet/try#590]
**Is your feature request related to a problem? Please describe.**
I am trying to run dotnet try in a docker container that has .NET Core 3 . 
Because of not letting me specify the domain, it cannot be seen outside the container

The docker file looks the following:
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
RUN dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" dotnet-try
ENV PATH="$PATH:/root/.dotnet/tools"
#ENV ASPNETCORE_URLS=http://+:5000
CMD dotnet try --verbose --port 5000 
EXPOSE 5000

Save the file above as console.docker  and run
 
docker build -f ./console.docker . -t drop
docker run --rm -it -p 5000:5000/tcp drop:latest

You will see that dotnet try is running on 
https://localhost:5000

that is not exposed in container to the host

**Describe the solution you'd like**
I want to can run such as the adress should be https://*:5000 , like here : https://github.com/aspnet/KestrelHttpServer/issues/2174

**Describe alternatives you've considered**
I do not see any alternatives

**Read More**
Please help

**Comment by jonsequitur** [comment]
We can help out here. The online Try .NET service also uses Docker.

Can you tell us more about what you want to use this for?

**Comment by ignatandrei** [comment]
Hello Jon
I want , when I make a software product or a presentation , to have a command line application that I can show to the users and they can run,with just Docker as dependency ( not the whole .NET Core SDK )
I was thinking at those steps:
0. Create the markdown files to see the projects
1. Deploy the .NET Core projects + markdown into a Docker with .NET Core SDK
2. Add dotnet try 
3. RUN dotnet try in Docker to see the markdown
4. RUN the docker image => container, see the dotnet try website .

As an example, please see https://github.com/ignatandrei/InfoValutar/

You can download the project and , if you go to the Interactive folder and run 
dotnet try  --port 5000

http://localhost:5000 
it works

However, if you want the docker files and run ( in the same folder)

docker build -f ./console.docker . -t drop
docker run --rm -it -p 5000:5000/tcp drop:latest

you have no answer from http://localhost

Please help

**Comment by ignatandrei** [comment]
Hey @jonsequitur 
At least one example how do you run dotnet try in Docker?

**Comment by jonsequitur** [comment]
Is your Dockerfile available to look at?

We're in the process of simplifying our own Dockerfile to remove the 2.1 SDK requirement and we might add it to the repo once that's done. I should warn you that this is a moving target in the meantime.

**Comment by ignatandrei** [comment]
Yes , it is . Please clone
https://github.com/ignatandrei/InfoValutar/
go to Interactive folder and run
docker build -f ./console.docker . -t drop
docker run --rm -it -p 5000:5000/tcp drop:latest

Where is your docker file ?

**Comment by ignatandrei** [comment]
Hello @jonsequitur  - could you point me to a valid Docker file to see how dotnet try works in container?
Thanks

**Comment by jonsequitur** [comment]
Here's an example but it's probably missing some pieces from our internal build setup. Simplifying this and making it better suited to support DIY web deployments is something we'd like to do though it's not something we can prioritize right yet.

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine3.9

# configure environment
ENV NUGET_PACKAGES=/dependencies/.nuget/packages
ENV TRYDOTNET_PACKAGES_PATH=/workspaces
ENV PATH "$PATH:/app/.dotnet/tools"

# install command line tools
RUN apk update
RUN apk add xmlstarlet
RUN apk add shadow

# set up the working directory where the Agent ASP.NET app runs
RUN mkdir -p /app
RUN groupadd app_group 
RUN useradd -r --gid app_group --home /app --shell /sbin/nologin --comment "app user" app_user 

COPY ./NuGet.Config /app/nuget.config
COPY . ./


RUN chown -R app_user:app_group /app
RUN chown -R app_user:app_group /workspaces
RUN chown -R app_user:app_group /dependencies/.nuget/packages
RUN chown -R app_user:app_group /tmp

RUN chmod -R 777 /root/

EXPOSE 4242

WORKDIR /app
USER app_user

ENV NUGET_XMLDOC_MODE=none
RUN dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19465.2

RUN dotnet tool install -g dotnet-try --version 1.0.19575.2 --add-source https://dotnet.myget.org/F/dotnet-try/api/v3/index.json 

RUN dotnet try pack /workspaces/project_blazor-nodatime.api --enable-wasm
RUN dotnet tool install blazor-nodatime.api --tool-path /workspaces --add-source /workspaces/project_blazor-nodatime.api --version 1.0.0
ENTRYPOINT ["dotnet", "try", "--port", "4242", "--verbose", "hosted" ]
```

**Comment by ignatandrei** [comment]
First, the command
ENV PATH "$PATH:/app/.dotnet/tools"
should be
ENV PATH="$PATH:/root/.dotnet/tools"
( missing = )

Second, the problem with version 1.0.19575.2
When I do run 
dotnet try --verbose --port 5000
( even on host computer ), it shows the .md files, but , when click the files, says not found
I do recommend version 1.0.19602.3

**Comment by ignatandrei** [comment]
There is a way to specify the .sln file and the .csproj file ? My csproj depends somehow of building the .sln ...

**Comment by ignatandrei** [comment]
I will open a new issue with the new problem

**Comment by sc1994** [comment]
> it shows the .md files, but , when click the files, says not found

I have encountered the same problem. Do you have any solutions?

**Comment by jamesmcconville** [comment]
> > it shows the .md files, but , when click the files, says not found
> 
> I have encountered the same problem. Do you have any solutions?

Works perfectly fine running natively in windows and linux. Is there any logs I can provide? Or point me to an open or closed issue specific to this problem?

**Comment by jamesmcconville** [comment]
I think I've hit the same issue.. The version mentioned as working (1.0.19602.3) seems unavailable.

Works perfectly fine running natively in windows and linux, but stick it in a docker container and despite the fact That a) try.net is running and B) The link to README.md is present, clicking on it gives a 404. .Is there any logs I can provide? Or point me to an open or closed issue specific to this problem?
