### ISSUE TITLE
FSharp Notebook sample is broken

### ISSUE THREAD

**Issue by yamachu** [dotnet/try#592]
#### Describe the bug
Please provide as much information as you can.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: Sample code is not working

#### Screenshots

When running this file, I got some errors.
https://github.com/dotnet/try/blob/001b36724d769e844a53b22e3833a23caed3dc68/NotebookExamples/fsharp/Samples/Repo%20Statistics.ipynb

```console
NET Core 向け Microsoft (R) Build Engine バージョン 16.3.0+0f4c62fea
Copyright (C) Microsoft Corporation.All rights reserved.

/var/folders/d1/gw65qzfn4q1gt2h22xz7hb440000gn/T/nuget/79462/Project.fsproj : error NU1101: パッケージ 2.4.6 が見つかりません。ソース local, nuget.org には、この ID のパッケージが存在しません。
/var/folders/d1/gw65qzfn4q1gt2h22xz7hb440000gn/T/nuget/79462/Project.fsproj : error NU1101: パッケージ 0.32.0 が見つかりません。ソース local, nuget.org には、この ID のパッケージが存在しません。
  /var/folders/d1/gw65qzfn4q1gt2h22xz7hb440000gn/T/nuget/79462/Project.fsproj の復元が 1.27 sec で失敗しました。
```

`/var/folders/d1/gw65qzfn4q1gt2h22xz7hb440000gn/T/nuget/79462/Project.fsproj` shows that
```
  <ItemGroup><PackageReference Include = 'Octokit' Version = '0.32.0'><GeneratePathProperty>true</GeneratePathProperty></PackageReference></ItemGroup>
  <ItemGroup><PackageReference Include = 'NodaTime' Version = '2.4.6'><GeneratePathProperty>true</GeneratePathProperty></PackageReference></ItemGroup>
  <ItemGroup><PackageReference Include = '0.32.0' Version = '*'><GeneratePathProperty>true</GeneratePathProperty></PackageReference></ItemGroup>
  <ItemGroup><PackageReference Include = '2.4.6' Version = '*'><GeneratePathProperty>true</GeneratePathProperty></PackageReference></ItemGroup>
```

It seems to be wrong that way to specify package version.
Actually in this PR (https://github.com/dotnet/fsharp/pull/7796/files#diff-e68c01be7bd8c62e32c0355823a810daR91) shows

```
#r "nuget:System.Collections.Immutable.DoesNotExist, version=1.5.0"
```

I'm already ready to submit Pull Requests that fix this issue
https://github.com/dotnet/try/compare/master...yamachu:fix-fsharp-sample

But README shows...
https://github.com/dotnet/try#contribution-guidelines

It would be better that I wait for a fix it?
Thanks.

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment]
@yamachu,

thanks for the notification.

The syntax for F# #r "nuget:" not requiring version= was updated in the F# repo, but it has not made it into the try.net repo yet.

Your PR looks good, please generate a PR for it, and we can consider merging it.

Thank you

Kevin

**Comment by KevinRansom** [comment]
@yamachu,
I have just synched and built the latest dotnet try and now the integrated F# supports the positional version argument :-)

Please re-open this issue if you still see the problem.  And thanks for the report.

Kevin
