### ISSUE TITLE
try.dot.net home page should have a title

### ISSUE THREAD

**Issue by kasiapusz** [dotnet/try#62]
try.dot.net should define a title for its home page so it appears more nicely in browsers :)
![29020016_10216085195746908_31220513_n](https://user-images.githubusercontent.com/28282763/37682047-ab301b58-2c45-11e8-86f1-020160d2d4f2.jpg)

**Comment by LadyNaggaga** [comment]
https://www.microsoft.com/net/platform/try-dotnet We have a new website
