### ISSUE TITLE
#r loads the oldest NuGet from the feed

### ISSUE THREAD

**Issue by tparviainen** [dotnet/try#624]
#### Describe the bug
Jupyter Lab / C# kernel, preview build of dotnet-try 1.0.19558.8 loads the newest (below v5.0.0) NuGet from the feed when the version is not defined in the #r command:
![image](https://user-images.githubusercontent.com/25169598/68540914-aa4ccf80-03a1-11ea-9b60-8ca01609f15c.png)

After upgrading to preview dotnet-try build 1.0.19558.9 the same #r command loads the oldest (below v1.0.0) NuGet package from the feed:
![image](https://user-images.githubusercontent.com/25169598/68540968-4d054e00-03a2-11ea-8d3c-430e50dd6603.png)

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: The default NuGet package should be the newest one when version is not given in the #r command.

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Thanks for reporting this @tparviainen. As a workaround while we fix this, you can specify the version number:

```csharp
#r "nuget:ClashOfClans,5.0.0"
```

**Comment by tparviainen** [comment]
Thanks @jonsequitur, I have been using next command as a workaround for this issue (it always loads the latest version and I do not need to know the exact version number of the latest NuGet package):
```
#r "nuget: ClashOfClans, *"
```
The output from the previous command is:
![image](https://user-images.githubusercontent.com/25169598/69733278-c6889480-1135-11ea-9a9f-ce8b1098807e.png)
