### ISSUE TITLE
Unable to use System.Text.Json iin Jupyter c# kernel

### ISSUE THREAD

**Issue by viblo** [dotnet/try#637]
#### Describe the bug
I just installed the c# jupyter kernel today for trying out. I can not get System.Text.Json namespace to import. If I do 
```using System.Text.Json;``` 
I get this error
 ```(1,19): error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)```
I also tried to reference it as a nuget package, with 
```#r "nuget:System.Text.Json"``` 
and it complete successful, but I still cannot use the namespace.

If I run ```Environment.Version``` from within the notebook I get 3.0.0 back. And ```dotnet --version``` shows 3.0.100 so I think I have the proper version installed.

I have installed some other packages, for example MongoDB.Driver could be installed with nuget and imported with using just fine, so it seems its something specifically with this package.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other:

#### Screenshots
![image](https://user-images.githubusercontent.com/1195272/68773618-32dea080-062c-11ea-864a-45b42dd6b7a5.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
    - [x] Firefox

**Comment by KevinRansom** [comment]
This works with the contents of master branch.
````
using System.Text.Json;
var jsonException = new JsonException();
var location = jsonException.GetType().Assembly.Location;
Console.WriteLine("{0}", location);
````

![image](https://user-images.githubusercontent.com/5175830/70752784-2bbcb800-1ce8-11ea-9824-ebe78bea8627.png)

I think I will update the test slightly though.
