### ISSUE TITLE
.net editor - Declare and use variables error

### ISSUE THREAD

**Issue by ozanyarci** [dotnet/try#64]
Hi,
I tried to teach my sister who is a doctor, c#. I encountered some problems. One of them is as follows:
When i changed example name from Bill to my name "Ozan Yarcı", an error was displayed.: "The service is temporarily unavailable. We are working on it." Can you solve this issue please? Ozan didnt work either.
https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-2

**Comment by jonsequitur** [comment]
Thanks, @ozanyarci. This was a transient issue and it has been fixed.
