### ISSUE TITLE
Clarify dotnet jupyter instructions

### ISSUE THREAD

**Issue by noahfalk** [dotnet/try#644]
#### Describe the bug
I was following the instructions at https://devblogs.microsoft.com/dotnet/net-core-with-juypter-notebooks-is-here-preview-1/.

Instead of running 'dotnet try jupyter install' within the Anaconda prompt I ran it at a regular terminal window which produced this output:

```
>dotnet try jupyter install
.NET kernel installation failed with error: Could not find jupyter kernelspec module
.NET kernel installation failed with error: Could not find jupyter kernelspec module
```

I recognize this was user error and corrected it. I am not blocked but wanted to suggest two things which may aid others not to make the same mistake:

1) In the directions at https://devblogs.microsoft.com/dotnet/net-core-with-juypter-notebooks-is-here-preview-1/ be more explicit that the command must be run in the Anaconda prompt. Re-reading certainly there is an implication that if bullet 3 is open a prompt then it is the context for bullet 4, but apparently while hoping back and forth between various windows and installing jupyter for the first time I missed that implication : ) Various cues that might have helped me:
- Using numbered steps instead of bullets to imply it is a sequence, not a set of independent pre-requisites for later
- Calling the bullets steps rather than 'you will need the following'
- Being explicit in step 4 that it is run at the anaconda prompt
- Showing the text of the Anaconda prompt at step 4

2) Adding a suggestion of what might be wrong to the error message. For example:
```
>dotnet try jupyter install
.NET kernel installation failed with error: Could not find jupyter kernelspec module
.NET kernel installation failed with error: Could not find jupyter kernelspec module
This command needs to be run from the Anaconda prompt. Did you run it elsewhere?
```

**Comment by LadyNaggaga** [comment]
Thanks for the feedback .  And something to consider for the github docs.  

![image](https://user-images.githubusercontent.com/2546640/68862256-22c1d200-06bb-11ea-8d3a-bd87bdf8fbcc.png)
