### ISSUE TITLE
.net editor - spacing error

### ISSUE THREAD

**Issue by ozanyarci** [dotnet/try#65]
When i change your example to following, error occured:  "The service is temporarily unavailable. We are working on it." Is spacing causes these errors? If i implemented in a wrong way, can you explain what i am doing wrong please?

https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-4

1)

string greeting = "      Hello World!       ";
Console.WriteLine($"[{greeting}]");
string trimmedGreeting = greeting.TrimStart();
Console.WriteLine($"[{trimmedGreeting}]");
trimmedGreeting = greeting.TrimEnd();
Console.WriteLine($"[{trimmedGreeting}]");

trimmedGreeting = greeting.Trim();
Console.WriteLine($"[{trimmedGreeting}]");

2)
Following also has problems with .net editor:

string greeting = "      Hello World!       ";
Console.WriteLine($"[{greeting}]");

string trimmedGreeting = greeting.TrimEnd();
Console.WriteLine($"[{trimmedGreeting}]");

trimmedGreeting = greeting.Trim();
Console.WriteLine($"[{trimmedGreeting}]");

**Comment by jonsequitur** [comment]
Thanks, @ozanyarci. The isssue should be resolved now. Please give it another try.
