### ISSUE TITLE
[.NET Kernel] [F#] Deedle / CSV Type Provider Support

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/try#656]
#### Describe the bug

Displaying a table using either Deedle or CSV Type Provider (FSharp.Data) does not render readable output. See attached screenshots. Below is the code used. The data comes from this dataset https://data.boston.gov/dataset/income-restricted-housing

```fsharp
#r "nuget:Deedle"
#r "nuget:FSharp.Data"

open Deedle
open FSharp.Data
open System.IO

//Define data path
let fileName = "income-restricted-housing.csv"
let dataPath = [|Path.GetFullPath "."; "data"; fileName|] |> Path.Combine

// Type Provider Section
type IncomeData = CsvProvider<"C:\Users\luquinta.REDMOND\Development\Notebooks\data\income-restricted-housing.csv">

let data = IncomeData.Load(dataPath)
data

data.Rows

// Deedle Section
let data = Frame.ReadCsv(dataPath)

data

data.Rows

(data.GetRow<string> 0).Values
```

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

##### FSharp.Data (CSV Type Provider)

![image](https://user-images.githubusercontent.com/46974588/69201462-63cb4380-0b0c-11ea-9dd7-97549560beb7.png)

##### Deedle

![image](https://user-images.githubusercontent.com/46974588/69201529-92e1b500-0b0c-11ea-9640-c16fcff318bb.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by zyzhu** [comment]
Deedle's formatter is related to #607 

The following snippet works for specific type of series as an example. But generic formatter is not gonna work yet. Try it in Jupyter lab.
```fsharp
open Microsoft.AspNetCore.Html
let formatOptionalValue (v:OptionalValue<_>) =      
  if v.HasValue then
    v.Value.ToString()
  else
    "N/A"
let registerSeries (s:Series<_,_>) (writer:TextWriter) =
    let headers = new ResizeArray<IHtmlContent> ()
    headers.Add(th.innerHTML(i.innerHTML("Key")))
    headers.Add(th.innerHTML(i.innerHTML("Value")))
    let rows = ResizeArray<ResizeArray<IHtmlContent>>()
    let take = 20
    let keys = s.Keys |> Array.ofSeq
    for i in 0 .. (Math.Min(take, int(s.KeyCount)) - 1) do
        let cells = ResizeArray<IHtmlContent>()
        cells.Add(td.innerHTML(box keys.[i]));
        cells.Add(td.innerHTML(s.TryGetAt(i) |> formatOptionalValue |> box));
        rows.Add(cells)
    let t =
        table.innerHTML(
            [|
              thead.innerHTML(headers)
              tbody.innerHTML(rows.Select(fun r -> tr.innerHTML(r)))
            |])
    writer.Write(t)

Formatter<Series<int,float>>.Register( (fun x writer -> registerSeries x writer), mimeType = "text/html")
[10, 1.; 20, 2.; 30, nan] |> series
Formatter<Series<int,string>>.Register( (fun x writer -> registerSeries x writer), mimeType = "text/html")
[1, "A"; 20, "B"; 30, "C"; 100, "D"] |> series

```
