### ISSUE TITLE
.net editor - Replace method error

### ISSUE THREAD

**Issue by ozanyarci** [dotnet/try#66]
Hi,
I have just changed Greetings to Creative but i got following error: "The service is temporarily unavailable. We are working on it." Can you help me to solve these issues please?

https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-4

string sayHello = "Hello World!";
Console.WriteLine(sayHello);
sayHello = sayHello.Replace("Hello", "Creative");
Console.WriteLine(sayHello);

**Comment by jonsequitur** [comment]
Thanks, @ozanyarci. The isssue should be resolved now. Please give it another try.
