### ISSUE TITLE
.net editor right click paste problem

### ISSUE THREAD

**Issue by ozanyarci** [dotnet/try#67]
Hi,
In this tutorial, https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world#step-1
I tried to teach c# to my sister who is a doctor. But there is no paste button if you right click the screen. So ctrl+v shortcut works but she doesnt know ctrl+v shortcut, so she needs a paste button. Can you help us?

**Comment by israelliberman** [comment]
Ctrl+V

**Comment by LadyNaggaga** [comment]
@ozanyarci thanks for the suggestion.  Would it be a better user experience if docs included a show me button similar to  what they have here https://www.microsoft.com/net/learn/in-browser-tutorial/3

**Comment by israelliberman** [comment]
I think it will be more convenient, and less confusing.

**Comment by rchande** [comment]
This is an issue with the underlying monaco editor: https://github.com/Microsoft/monaco-editor/issues/391#issuecomment-312237052. Browsers other than Internet Explorer don't allow websites to paste from the clipboard, so there's no reason to have a paste button. @ozanyarci if this is a major issue for you, consider using Internet Explorer.
