### ISSUE TITLE
Service temporarily unavailable

### ISSUE THREAD

**Issue by nkroker** [dotnet/try#7]
when I was trying to run my code on C# online compiler then it not running and says that ""This service is temporarily unavailable"

**Comment by piotrpMSFT** [comment]
@nkroker thanks. We're working on a guide for helping folks notify us of Service Unavailable issues. For the time being, if you're able to get the response from your browser [including headers] and share it, it will make diagnosis much easier.

**Comment by jaxidian** [comment]
I am able to reliably reproduce it with some silly yet valid code. In my case, I assume this is an intentional protection mechanism in place.

Code:

```
int[] ar = Enumerable.Range(0, int.MaxValue / 2).ToArray();

foreach (int element in ar)
{
    System.Console.WriteLine(element);
}
System.Console.WriteLine();
```

Sanitized Response Headers:

```
Cache-Control:no-cache, no-store
Content-Length:0
Content-Security-Policy:default-src 'none';script-src 'self' https: 'sha256-stuff' 'sha256-stuff';style-src 'self' https: 'unsafe-inline';child-src 'self';connect-src 'self' https:;img-src 'self' https: data:;frame-ancestors https://docs.microsoft.com
Date:Wed, 18 Oct 2017 21:14:15 GMT
Pragma:no-cache
Request-Context:appId=stuff
Request-Id:|27a7434f-44f59ddecb9e17c5.1.2.323.1.
Set-Cookie:XSRF-TOKEN=stuff; path=/; secure
Set-Cookie:dotnet-repl=stuff; expires=Wed, 18 Oct 2017 21:34:15 GMT; path=/; secure; samesite=lax; httponly
X-Content-Type-Options:nosniff
```

**Comment by jonsequitur** [comment]
@jaxidian Yes, running code like this will give you an error after a while. We'll improve the response to be a bit clearer about what happened.
