### ISSUE TITLE
Create a directory

### ISSUE THREAD

**Issue by israelliberman** [dotnet/try#70]
Create a directory named branches-quickstart. 
Make that the current directory and run dotnet new console -n BranchesAndLoops -o .. 
This command creates a new .NET Core console application in the current directory.

How do I do this?
This is the first time, and I do not understand the issue of versions yet :(

**Comment by jmarolf** [comment]
@israelliberman from the console run these commands:
```
mkdir branches-quickstart.
cd branches-quickstart.
```

I would also look at this documentation: https://www.microsoft.com/net/learn/get-started/windows
