### ISSUE TITLE
Publish the source code

### ISSUE THREAD

**Issue by atifaziz** [dotnet/try#71]
I understand that the [README](https://github.com/dotnet/try/blob/03be2aa6eed2298875988df535f0b3b14addbb15/README.md) clearly [states](978c45363c41dd3194738d08c439078c66451a83):

> - **Please Note**: The code for Try .NET is not currently hosted on GitHub.

I'm nonetheless opening this issue for votes/discussion and to give @LadyNaggaga a place to post the good news :wink: when the source is available and open to contributions.

The ability to run and try C# samples interactively in the browser will benefit many package authors/maintainers (and the dotnet community at large) by enabling them to offer tutorials to users.

**Comment by ogrim** [comment]
Source is published, we did it! 🎆

**Comment by atifaziz** [comment]
Awesome!
