### ISSUE TITLE
F# JupyterLab DataFrame Example Doesn't Load

### ISSUE THREAD

**Issue by seth-ahca** [dotnet/try#714]
#### Describe the bug
The online F# DataFrame example doesn't load for me, and instead returns this error:

File Load Error for DataFrame-Getting Started.ipynb
Unreadable Notebook: /home/jovyan/Notebooks/fsharp/Samples/DataFrame-Getting Started.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

It looks like the latest commit (fe9d31e, #700) to the file (NotebookExamples/fsharp/Samples/DataFrame-Getting Started.ipynb) may have broken the format. Line 73 ("let df = DataFrame([dateTimes; ints; strings]: DataFrameColumn list)\n",) should not have the trailing comma, I think.

Thank you.

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [X] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: JSON file doesn't load

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari
    - [X] FireFox

**Comment by pgovind** [comment]
This should be fixed with https://github.com/dotnet/try/pull/720

**Comment by seth-ahca** [comment]
It's working now, thank you.
