### ISSUE TITLE
无法进入焦点模式

### ISSUE THREAD

**Issue by L261173157** [dotnet/try#721]
#### Describe the bug
打开C#交互学习时，无法进入焦点模式

#### Did this error occur while using `dotnet try` or online?
- [x] online

#### What kind of error was it?

- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"

#### Please complete the following:
 - OS
    - [x] Windows 10

 - Browser 
    - [x] Chrome

**Comment by jonsequitur** [comment]
> "Cannot enter focus mode when C # interactive learning is turned on" (trans.)

Could you provide a screen shot? And if you open the Chrome vev tools console, are you seeing any JavaScript errors?

**Comment by L261173157** [comment]
> > "Cannot enter focus mode when C # interactive learning is turned on" (trans.)
> 
> Could you provide a screen shot? And if you open the Chrome vev tools console, are you seeing any JavaScript errors?

today,it's ok. thank you
