### ISSUE TITLE
Dotnet try command fails on Manjaro.

### ISSUE THREAD

**Issue by Yucked** [dotnet/try#722]
I was following the guide given [`here`](https://devblogs.microsoft.com/dotnet/net-core-with-juypter-notebooks-is-here-preview-1/) but running `dotnet try juypter install` gives the following exception.

```
[yucked@SR98 ~]$ dotnet try juypter install
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/yucked/.dotnet/tools/.store/dotnet-try/1.0.19553.4/dotnet-try/1.0.19553.4/tools/netcoreapp3.0/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=manjaro-x64
```

I've installed .NET Core 3.1 via [`dotnet-install-scripts`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)

I've added dotnet core path in my `bashrc`:
```
# ANACONDA
PATH=/home/yucked/anaconda3/bin:$PATH

# DOTNET
PATH=/home/yucked/.dotnet:$PATH
PATH=/home/yucked/.dotnet/tools:$PATH

export PATH
```

And my dotnet info is as follow:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/yucked/.dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/home/yucked/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/home/yucked/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/home/yucked/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I've read couple of solutions and all of them end up being about `PATH` not configured but mine works properly AFAIK.

**Comment by jonsequitur** [comment]
Do you get this issue as well if you don't customize your path manually via `.bashrc`? That's not typically needed.

**Comment by Yucked** [comment]
If I don't add it manually to the path, it doesn't recognize `dotnet` or `dotnet try`. `dotnet-install-scripts` doesn't add dotnet to PATH and I've to manually do that. Writing `export PATH=....:$PATH` only works for the console window I type it in and I'd have to type that in each time I open a new console window or restart my machine. Also problem stated on this [SO](https://stackoverflow.com/questions/53182688/dotnet-install-sh-not-adding-dotnet-command-on-ubuntu).

**Comment by jonsequitur** [comment]
Is the issue specific to `dotnet-try` or are other .NET global tools also affected?

**Comment by Yucked** [comment]
I haven't tried any other tools besides dotnet-try. If there is a list of any other tools that I can install and report back on, I can do so when I wake up. That will definitely help narrow down the problem.

**Comment by jonsequitur** [comment]
Here's a good simple one: https://www.nuget.org/packages/dotnet-cowsay/

**Comment by Yucked** [comment]
Okay, it seems to be a problem with `dotnet` itself.
```
[yucked@SR98 ~]$ dotnet tool install --global dotnet-cowsay --version 1.3.0
You can invoke the tool using the following command: dotnet-cowsay
Tool 'dotnet-cowsay' (version '1.3.0') was successfully installed.
[yucked@SR98 ~]$ dotnet-cowsay
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/yucked/.dotnet/tools/.store/dotnet-cowsay/1.3.0/dotnet-cowsay/1.3.0/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=manjaro-x64
```

**Comment by Yucked** [comment]
Okay, I see to have fixed it. It seems it was looking for `DOTNET_ROOT` env variable and I added it to `bashrc` which fixed it. Thank you!
