### ISSUE TITLE
.NET Editor interactive (online) does not accept edits after the first >run command was issued

### ISSUE THREAD

**Issue by boulderdasher** [dotnet/try#73]
The online editor is non-functional after the first >run button/command was issued. Page with issue is: https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp#step-1

**Comment by javierlf** [comment]
Mismo problema
Same problem

**Comment by javierlf** [comment]
En todas las páginas
No page is working

**Comment by Zyphruss** [comment]
It's working fine in Microsoft Edge but only runs once and then makes the input area read-only in Firefox, for me.

**Comment by jonsequitur** [comment]
This is a duplicate of #17.
