### ISSUE TITLE
.net editor does not display output

### ISSUE THREAD

**Issue by smitty65** [dotnet/try#774]
on Mac OS Catalina

**Comment by LadyNaggaga** [comment]
Hi @smitty65 is this happening on docs.microsoft.com or dotnet try?  What browser are you using?

**Comment by smitty65** [comment]
docs.microsoft.com, and safari browser. It is working on my Firefox browser though so its all good

**Comment by LadyNaggaga** [comment]
Yes, this Safari bug resurfaced with Catalina please see this [issue](https://github.com/dotnet/try/issues/500 ) we are monitoring it.  Since, this is a duplicate issue I will closing it. And please feel free to follow the issue here https://github.com/dotnet/try/issues/500
