### ISSUE TITLE
A11y_A11y_.NETOnlineREPL_Benchmark_.NET Editor_Screen reader: Unnecessary hidden content is read by the screen readers in the output section.

### ISSUE THREAD

**Issue by Charanrajkb** [dotnet/try#791]
**Environment details:**
https://docs.microsoft.com/
Browser: Chromium Edge Version 80.0.361.50 (Official build) (64-bit)
OS Details:Windows 10 

GitHubTags:#A11yTCS;#A11ySev2;#A11y_.NETOnlineREPL_Benchmark;#.NET Online REPL;#Benchmark;#DesktopWeb;#Win10;#MAS1.3.1;#Accessibility;#.NET Online REPL;#Narrator;#NVDA;#ChromiumEdge;#Chrome;#A11yMAS;

**​Repro Steps:​**
1.Hit the URL "https://docs.microsoft.com/" and login with appropriate credentials.
2.Tab till "Enter focus Mode" button and press enter.
3.Start narrator and navigate using the caps + Arrow till the output section.
4.Observe the narrator readings.

**Actual Result:​**
When we navigate using the caps + arrow while the narrator is on is read the Hello world  welcome to your new app, Array accepted is read which is hidden content.

**Expected Result:​**
Narrator must not read the hidden content in the output section.

**User Impact:​**
Screen readers users will find difficulty in understanding the content present in the output section.

**Attachment:**
[791_A11y_.NETOnlineREPL_.NET Editor_Screen reader.pptx](https://github.com/dotnet/try/files/4207911/791_A11y_.NETOnlineREPL_.NET.Editor_Screen.reader.pptx)

**Comment by LadyNaggaga** [comment]
@Charanrajkb This is an external bug and I have notified the docs team here https://github.com/MicrosoftDocs/feedback/issues/2532.

**Comment by saadtaeh** [comment]
Thank you for Continue.

**Comment by keerthiduvvuri** [comment]
#Closed;
