### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by mika76** [dotnet/try#803]
Wouldn't it be better to run this as a repl? So only expressions can be written and just stating the variable will show its output?

**Comment by jonsequitur** [comment]
Have you taken a look at [dotnet-interactive](https://github.com/dotnet/interactive)? It's focused currently on providing support for notebooks (including Jupyter), but we might look into building a command-line REPL for it as well.

There are definitely overlapping use cases between the two tools. The general goal of `dotnet-try` is to provide guided interactive documentation, whereas the goal of `dotnet-interactive` is to enable freeform experimentation and exploration. For C# in particular, the scripting variant is different enough from the core language that we found that a REPL wasn't ideal for people looking to learn to build .NET applications.

**Comment by mika76** [comment]
@jonsequitur I hadn't seen it - I'll take a look...
