### ISSUE TITLE
Incorrect use of max

### ISSUE THREAD

**Issue by Seymog** [dotnet/try#816]
On https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=3

It uses max instead of int.MaxValue in the code snippet:

int what = max + 3;
Console.WriteLine($"An example of overflow: {what}");

**Comment by Martin005** [comment]
Before the code snippet, the docs say "Add these two lines to the interactive window to see an example:", so the "max" refers to the variable previously declared to have the "int.MaxValue" value.
