### ISSUE TITLE
No se puede modificar el código después de la ejecución 

### ISSUE THREAD

**Issue by iD3us** [dotnet/try#82]
Modificar el código después de modificarlo, es imposible. La única solución que encontré fue dar clic derecho en el código para seleccionar la opción cortar del menú contextual. Solo de esa manera se puede modificar el código. Además no se puede borrar el código después de su ejecución, al dar clic en la tecla borrar me direcciona a una pagina previa de mi navegador.

**Comment by LadyNaggaga** [comment]
Closing this issue since it seems to be caused by a temporary bug.  Please let us know if it continues.

Lo siento - estoy usando el traductor de google
Cerrar este problema ya que parece ser causado por un error temporal.
Por favor, háganos saber si continúa.
