### ISSUE TITLE
"dotnet try jupyter install" gives error: "Required argument missing for command: install"

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/try#820]
#### Describe the bug
I am following this tutorial by Scott: https://www.hanselman.com/blog/AnnouncingNETJupyterNotebooks.aspx
On how to get Jupyter set up with .net. I have folowed all the steps as written, then uninstalled and redone the steps three times, (also re-install the .net core SDK). This makes no sense and googleling it gives litterally no results other than tutorials that displays the command "dotnet try jupyter install".

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other:  "Required argument missing for command: install"

#### Screenshots
![image](https://user-images.githubusercontent.com/13543585/79120292-d4604e80-7d92-11ea-831d-9c9cd74e35e0.png)

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Support for Jupyter for .NET has moved out to its own project, .NET Interactive. Please try out the installation instructions here: https://github.com/dotnet/interactive

**Comment by LadyNaggaga** [comment]
@frankhaugen Scott Hanselman wrote an update to the post you referenced here https://www.hanselman.com/blog/AnnouncingNETInteractiveTryNETIncludesNETNotebooksAndMore.aspx

**Comment by frankhaugen** [comment]
@jonsequitur @LadyNaggaga Thank you both for your time! Now it works, and I'm closing this as resolved. Keep up the  👍
