### ISSUE TITLE
trydotnet.microsoft.com 503 Application Error

### ISSUE THREAD

**Issue by franky920920** [dotnet/try#823]
#### Describe the bug
Please provide as much information as you can.
editor return a 503 error.
#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [x] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [x] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![image](https://user-images.githubusercontent.com/11349917/79524034-15f24180-8092-11ea-8588-1542c4ba5ae8.png)
![image](https://user-images.githubusercontent.com/11349917/79524066-26a2b780-8092-11ea-959d-d4f19694dd4a.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [ ] Safari

**Comment by Martin005** [comment]
It also doesn't work on Firefox:
![obrazek](https://user-images.githubusercontent.com/10096404/79563841-d3d6f900-80ad-11ea-86ec-bcea7f6e40c8.png)

**Comment by jonsequitur** [comment]
Thanks. This has been resolved.

**Comment by Martin005** [comment]
@jonsequitur Please close #822 as well, it's a duplicate.
