### ISSUE TITLE
Error in value output

### ISSUE THREAD

**Issue by RichardSmanhoto** [dotnet/try#828]
#### Describe the bug
Error found in execution when the displayed value is incorrect in relation to the actual calculation value. 
I believe it is a mistake.

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [x] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: miscalculation

#### Screenshots
![Error](https://user-images.githubusercontent.com/62729602/80291940-5142df00-8728-11ea-8831-92fa1c51727f.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by svick** [comment]
You're using integers, so the `/` operator computes integer division. That means the value of `1/2` is `0` (0.5 cannot be represented as an integer). That means the output is correct.

**Comment by RichardSmanhoto** [comment]
Wow! Really! I'm sorry for the issue unwanted
