### ISSUE TITLE
This sentence is not proper English.

### ISSUE THREAD

**Issue by LouieInSeattle** [dotnet/try#83]
This sentence is not proper English.  Should it read "...even try not implementing the..."?
Even then it is not clear.  
   "You might even not implement ToString method since every C# data type has some implementation of this method. "

**Comment by mairaw** [comment]
@rpetrusha @BillWagner to take a look. This seems to be in the interpolated strings tutorial.

**Comment by rpetrusha** [comment]
Thanks, @LouieInSeattle, for pointing this out. We've opened dotnet/docs#5545 to address the issue.

//cc @mairaw @BillWagner

**Comment by BillWagner** [comment]
Fixed in dotnet/docs#5545. Closing.
