### ISSUE TITLE
Launching mybinder on dotnet/try repo does not offer .NET kernel

### ISSUE THREAD

**Issue by JuanjoFuchs** [dotnet/try#831]
#### Describe the bug
When launching mybinder with this URL: https://mybinder.org/v2/gh/dotnet/try/master?urlpath=lab
it loads JupyterLab fine and without errors, but ".NET (C#)" Kernel is not available. Only Python.

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [ ] online
- [X] MyBinder.org

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: .NET kernel not available

#### Screenshots
![image](https://user-images.githubusercontent.com/1458518/80652795-5660a080-8a3e-11ea-9d6e-03d8d9d67e82.png)

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
.NET support on Jupyter has moved from the `dotnet-try` project to `dotnet-interactive`. You can find the Binder link here: https://github.com/dotnet/interactive

**Comment by colombod** [comment]
I am closing this issue
