### ISSUE TITLE
hide the output on try.dot.net

### ISSUE THREAD

**Issue by liuxilu** [dotnet/try#836]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a control to hide output and/or adjust its height.

**Describe alternatives you've considered**
Tried to use DevTool.

**Read More**
https://github.com/dotnet/try/wiki/Project-Roadmap

**Comment by jonsequitur** [comment]
Why do you want to hide the output?

**Comment by liuxilu** [comment]
It occupies half screen, not easy to type.
