### ISSUE TITLE
"$" displays as an ascii square. 

### ISSUE THREAD

**Issue by c4ss4ndr4** [dotnet/try#84]

**Comment by c4ss4ndr4** [comment]
Attached is a screenshot of the output window. 

[Screenshot Tutorial bug.pdf](https://github.com/dotnet/try/files/2028955/Screenshot.Tutorial.bug.pdf)

**Comment by svick** [comment]
That's actually the correct result. The symbol you see, ¤, is the "[currency sign](https://en.wikipedia.org/wiki/Currency_sign_(typography))", used by .Net as the currency symbol for the invariant culture, which is the culture used by Try.Net.

See also https://github.com/dotnet/docs/issues/5440.
