### ISSUE TITLE
'Connection aborted' errors on launch

### ISSUE THREAD

**Issue by selfagency** [dotnet/try#840]
#### Describe the bug

The web server drops all connections.

```
http: error: ConnectionError: ('Connection aborted.', OSError(0, 'Error')) while doing a GET request to URL: https://localhost:57577/
```

The same call when made with the server unloaded:

```
http: error: ConnectionError: HTTPSConnectionPool(host='localhost', port=57577): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1088450a0>: Failed to establish a new connection: [Errno 61] Connection refused')) while doing a GET request to URL: https://localhost:57577/
```

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: 

```
http: error: ConnectionError: ('Connection aborted.', OSError(0, 'Error')) while doing a GET request to URL: https://localhost:57577/
```

#### Screenshots
<img width="1473" alt="Screenshot 2020-05-20 20 47 47" src="https://user-images.githubusercontent.com/2541728/82511408-3cfdc200-9adb-11ea-81ea-3565f8926b1d.png">

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Are you seeing this in the browser as well?

Also, what version of `dotnet-try` are you using?

**Comment by selfagency** [comment]
Yes it happens in the browser as well and I'm using the whatever is the latest installed via dotnet-cli, so I assume the latest. Not at desk at.

**Comment by jonsequitur** [comment]
Could you run `dotnet try --version` and post the output?

Thanks.

**Comment by selfagency** [comment]
1.0.20270.2+877c25cb80baa7785c56f6a74f549007d603073b

**Comment by colombod** [comment]
Are you using the package with name `dotnet-try` or `Microsoft.dotnet-try` ?

**Comment by Denpex** [comment]
> Are you using the package with name `dotnet-try` or `Microsoft.dotnet-try` ?

I have the same issue persisting on all 3 major browsers: Chrome, Safari & FireFox tested on both macOS 10.15.4 & 10.15.5

dotnet-try version: 1.0.20305.1+a5177e5bf1d0589f520abe3a96eeed3b2c4b2c86

**Comment by selfagency** [comment]
closing this because it's 2 years old, i haven't touched c# since then, and i want to clean up my issues tab
