### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by logeshpalani32** [dotnet/try#852]
#### Describe the bug
Please provide as much information as you can.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [x] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![Screenshot 2020-06-27 at 3 04 32 PM](https://user-images.githubusercontent.com/24875197/85919332-d57c2480-b887-11ea-9230-9e8a5e6b151d.png)

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Which version of dotnet try are you using?

**Comment by logeshpalani98** [comment]
@jonsequitur  --version 1.0.19553.4

**Comment by SumanPadhy91** [comment]
Same issue with me in Windows 10, Chrome Browser, version 1.0.19553.4

Error found in Console:
![image](https://user-images.githubusercontent.com/62999108/86536055-4a8fcf80-bf02-11ea-8cc3-3fcb1551c1e8.png)

**Comment by SumanPadhy91** [comment]
@logeshpalani98 try using microsoft.dotnet-try, had the same issue which got resolved by updating the package.

**Comment by DylPickle11** [comment]
I am also having this same issue and have the most up to date version

**Comment by jonsequitur** [comment]
@DylPickle11 Could you post the results of `dotnet --info` and `dotnet tool list -g`?

**Comment by DylPickle11** [comment]
@jonsequitur 
Absolutely! .NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by DylPickle11** [comment]
dotnet tool list -g
Package Id                Version          Commands  
-----------------------------------------------------
microsoft.dotnet-try      1.0.20268.1      dotnet-try

**Comment by phenixita** [comment]
Try with uninstalling dotnet try and reinstall it with:
`> dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-try`

CC: @colombod
