### ISSUE TITLE
Clicking Editor Fails to Focus

### ISSUE THREAD

**Issue by prail** [dotnet/try#86]
### Platform:
Waterfox 56.2.0 with uBlock Origin and Dark Reader extensions installed Stylo is enabled as well.
### Bug:
It seems that on the C# Hello World interactive [tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=3), mouse clicks fail to focus on the text entry. This problem should be reproduceable on all of the .NET try lessons.
### Video:
[Here](https://streamable.com/v3kky) is a video of it in action.

**Comment by Icemole** [comment]
I have had the same issue, when I clicked Run the code was not editable anymore. In my case, I worked around it by refreshing the page every time I clicked Run.

**Comment by jonsequitur** [comment]
This was likely another example of #17 and if so, it's now fixed. @prail Please reopen this if it's still not working for you.
