### ISSUE TITLE
Try-samples can't lauch

### ISSUE THREAD

**Issue by jasonl1994** [dotnet/try#870]
#### Describe the bug
Hello, I am complete beginner for .NET CORE. I come across dotnet try when I browse Documentation Page to find more  sample code to learn about LINQ. I followed the instructions to try to get try-samples run, but it never did.

Here is the screenshot:
[Imgur](https://imgur.com/qr3blEU)

I notice that I'm having an incorrect Content Root Path when trying to run the samples since it should be the path to where the sample codes are stored. I couldn't find anyone having similar problem after the search.

Really appreciate if anyone could help.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Could you try launching it in standalone terminal instead of the Visual Studio PowerShell prompt?
