### ISSUE TITLE
C# tutorial "Explore integer precision and limits" 

### ISSUE THREAD

**Issue by MechaFlyer** [dotnet/try#88]
Running this code block
`int what = max + 3;
Console.WriteLine($"An example of overflow: {what}");`

Produces this error in the online coder:
(1,12): error CS0103: The name 'max' does not exist in the current context

Which supposedly should produce the number -2147483646 as the tutorial states

**Comment by jonsequitur** [comment]
The [sample ](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp?tutorial-step=3#step-2) says "Add these two lines to the interactive window to see an example:" above the snippet, but if you try to run the third snippet by itself, you get this compilation error.

@BillWagner

**Comment by BillWagner** [comment]
I'd like to close this.  The instructions are clear around those two snippets. 

@MechaFlyer If you are still having issues, re-open the issue and let me know what you would want different in the explanation.
