### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qjoner** [dotnet/try#884]
#384 ## Describe the bug
Please provide as much information as you can.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [x] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [x] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by qjoner** [comment]
Hello

**Comment by TheKing505** [comment]
Hello Universal Virgo
