### ISSUE TITLE
The dotnet try app doesn't work on macOS

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/try#888]
I just cloned the command-line-api repo as instructed, installed dotnet-try and fired it up

```bash
dotnet try docs 

Welcome to Try .NET!
---------------------
Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience.The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_TRY_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Hosting environment: Production
Content root path: /Users/mgwelch/.dotnet/tools/.store/microsoft.dotnet-try/1.0.20268.1/microsoft.dotnet-try/1.0.20268.1/tools/netcoreapp3.1/any
Now listening on: https://localhost:64005
Application started. Press Ctrl+C to shut down.
```

But neither safari nor edge can access that port:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/826112/88432772-7516cf00-cdc2-11ea-9f23-ac6767864483.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/826112/88432798-84961800-cdc2-11ea-98b8-4bb1157665fb.png">

**Comment by jonsequitur** [comment]
Please update to the latest `Microsoft.dotnet-try` package and latest .NET Core 3.1 SDK and let us know if this helps.

**Comment by saadtaeh** [comment]
Before I forget, Wind's re-desktop. When you want to break the passcode? 
How do you fix it?

**Comment by jonsequitur** [comment]
If this did not solve the problem, please reopen the issue.

**Comment by werner-traut** [comment]
I tried using dotnet try 1.0.21110.1+c2137652ada27a9795475eee75f8dbc8869f63b1 on Mac OS Big Sur v11.2.1 and get this same issue.

**Comment by Hultner** [comment]
Doesn't work for me either.
