### ISSUE TITLE
Empty red area is displayed after Run button is clicked

### ISSUE THREAD

**Issue by okikh** [dotnet/try#894]
#### Describe the bug
I am using **dotnet try** to test c# pattern matching feature. This is my repo (and branch where the bug is reproduced):
https://github.com/kihtov23/csharp-pattern-matching/tree/bug_red_box_displayed
Steps to reproduce:
1. Run "dotnet try" on .csharp-pattern-matching/CSharpPatternMatching/ folder
2. Click "Run" button on first code sample. Expected result is 14 and actual result is 14 so it works fine.
3. Click "Run" button on second code sample. Expected result should be concrete numbers
but actual result is this red box:
![image](https://user-images.githubusercontent.com/71128280/99224475-0d601600-27ef-11eb-88a6-046d7b7dd8ff.png)

#### Did this error occur while using `dotnet try` or online?
- `dotnet-try`

#### What kind of error was it?
-  User Interface (UI):  For example the output never displayed 

#### More details:
 - OS
    - Windows 10

 - Browser 
    -  Chrome

**Comment by jonsequitur** [comment]
Can you post the output of `dotnet --info` and `dotnet try --version`?

**Comment by okikh** [comment]
Here it is: 
dotnet --info
![image](https://user-images.githubusercontent.com/71128280/99502465-c3f5ff00-2985-11eb-9e7d-16d3240e7f5c.png)

dotnet try --version
![image](https://user-images.githubusercontent.com/71128280/99502511-d708cf00-2985-11eb-81cc-a3b918290aeb.png)
1.0.20474.1+b813993a08b02779772f65bc2881b9b9fbb2d957

**Comment by JeanCollas** [comment]
Same here...

PM> dotnet --info
SDK .NET Core (reflÃ©tant tous les global.json)Â :
 Version:   3.1.302
 Commit:    41faccf259

Environnement d'exÃ©cutionÂ :
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PM> dotnet try --version
1.0.20512.1+aca212da7cd062d22cce8fbca8acb5cb848929b7

**Comment by colombod** [comment]
I am running your same version, my machine was recently reinstalled.
I run with occasional red box only on first run after cloning your repo.

Does it work at all for you?

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by okikh** [comment]
What do you mean by "Does it work at all for you?"? Do you mean whether I can see red area or whether I see page in browser when run "dotnet try"? 
I described steps in my original message: "dotnet try" works fine, I can see the page on browser but I see red box when clink "Run" buttons on that web page. Please check my original message and if there is any missing details there please let me know so I will add them.

**Comment by colombod** [comment]
Hi @okikh I am asking if the red box is constantly and consistently coming up for you and therefore you have no way to execute those cell successfully, or if it is a transient error that lets you perform runs eventually.

As you can see
![image](https://user-images.githubusercontent.com/375556/101911893-e829b200-3bb8-11eb-8202-88b50cafbe08.png)

I run all three cells no problem

**Comment by okikh** [comment]
I updated .NET SDK recently. My current one is:

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
-----

And when I run "dotnet run" now on the same folder - the issue is not reproducable.
So I can close the issue.

**Comment by okikh** [comment]
Once I updated .Net version on my PC - issue's gone.

**Comment by abdou31** [comment]
How to update?

**Comment by kihtov23** [comment]
Download and install new .NET SDK
https://dotnet.microsoft.com/download/dotnet
as of 14th of May 2021 - .net 5 is recommended to install by Microsoft (if your current project does not require some older version)
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by abdou31** [comment]
There is no change, the red area still exists and the issue persists.

**Comment by abdou31** [comment]
> Once I updated .Net version on my PC - issue's gone.

The issue was not gone in my case !!!
