### ISSUE TITLE
See what library namespaces are available - valid usings

### ISSUE THREAD

**Issue by JamesReate** [dotnet/try#9]
It would be nice to know what valid library namespaces are available. For example I tried `using System.Net.Http` but it was not available. Instead of having to try what I can use and can't use it would be useful to have a searchable list somewhere.

**Comment by piotrpMSFT** [comment]
@rchande is this scenario covered by your current completions work?

**Comment by rchande** [comment]
The new completions feature will guide you through adding this. I verified that namespaces show up after `using`.

**Comment by JamesReate** [comment]
Looks like it works! awesome, thanks Ravi
