### ISSUE TITLE
Does TryDotNet support C#9 ?

### ISSUE THREAD

**Issue by aimenux** [dotnet/try#910]
Hi,
I m trying to build some interactive demo about c# 9 based on TryDotNet.
But i have various compilation errors when i launch the demo.
My project (net 5 console app) builds without errors under VS.
Is TryDotNet supporting C# 9 ? How to enable this ? Do you have some sample ?
Below my code and screenshot errors.
Thanks for such great tool !

```csharp
public static class CSharp9
{
        public static int PatternMatching()
        {
            #region PatternMatching

            static bool IsLetter(char c) => c is >= 'a' and <= 'z' or >= 'A' and <= 'Z';
            Console.WriteLine($"5 is letter ? {IsLetter('5')}");

            #endregion

            return 0;
        }
}
```
![image](https://user-images.githubusercontent.com/13971666/107400794-76aba880-6b02-11eb-9630-831ea2b39faa.png)

**Comment by jonsequitur** [comment]
C# 9 is not currently supported. In the meantime, would [.NET Interactive](https://github.com/dotnet/interactive) suit your needs?

**Comment by aimenux** [comment]
@jonsequitur thanks for your reply, i will try the suggested alternative.
