### ISSUE TITLE
Try .NET Improvement

### ISSUE THREAD

**Issue by colombod** [dotnet/try#984]
- [X] implement new wasmrunner
  - [X] create wasmrunenr and integration tests via messaging api
  - [X] configure runner iframe via client-data attributes
- [x] create new editor endpoint using update Monaco component
- [x] test sending run request via iframe messages
- [x] #996 (@colombod)
  - [x] implement focus api call 
  - [x] review `generateregionfromfiles` request and response
  - [X] review api / usage for scaffolding
  - [x] review api / usage for hide and show editor
- [x] #997 (@brettfo)
  - [x] diagnostics in editor
  - [x] signaturehelp in editor
  - [x] signaturehelp with documentation in editor
  - [x] completions in editor
  - [x] completions with documentation in editor
- [x] setup new build infrastructure
  - [x] setup ci
  - [x] setup deployment via EV2
  - [x] setup PME environment
  - [x] tests https behaviors as post deployment in staging
  - [x] certificates are setup with correct rotations in PME environments
 - [x] figure out packaging story for tool and dependencies

**Comment by Nirmal4G** [comment]
Currently Try.NET only executes with a POSIX platform context. What this means that we can't quickly paste a snippet of code that work only on Windows to verify/validate across 3 major OS types. So, Please allow choosing between Windows, Mac and other Linux distributions (most used one like Ubuntu or Kali or Debian). Also allow standard input and cmd-line invocation parameters to be specified.
