### ISSUE TITLE
Feature Request: Preload `System.Memory` NuGet package

### ISSUE THREAD

**Issue by BillWagner** [dotnet/try#99]
This package is required for any samples that use `Span<T>` and friends.  See https://github.com/dotnet/docs/pull/6225#issue-198399416 for details.

/cc @pkulikov

**Comment by pkulikov** [comment]
Related (or duplicate) of #85

**Comment by LadyNaggaga** [comment]
@TheRealPiotrP  @colombod @jonsequitur could we please get the above NuGet package into the pipeline.

**Comment by pkulikov** [comment]
As for now, [try.dot.net](https://try.dot.net/) accepts `Span<T>`. @LadyNaggaga thanks a lot!
