### ISSUE TITLE
update trydotnet.js to integrate with new editor api

### ISSUE THREAD

**Issue by colombod** [dotnet/try#996]
- [X] adapt trydotnet js api to the new monaco component
  - [X] update messages to use new objects and types
  - [x] create integration tests 
  - [X] loading the iframe using mscode code
  - [x] executing code
  - [x] testing languageservices
  - [x] ci for winfows and linux with blame timeout
  - [ ] packaging for the tool
  - [ ] PME deployment to staging environment

**Comment by EssaAlKazem** [comment]
[https://github.com/dotnet/try/issues/996#issue-1208908009](url)
